dimod/samplers/brute_force.py, dimod/samplers/random_sampler.py, dimod/samplers/simulated_annealing.py, dimod/samplers/tests/generic_sampler_tests.py, dimod/samplers/tests/test_brute_force.py, dimod/samplers/tests/test_simulated_annealing.py
Fix typos and make minor tweaks to punctuation and wording for clarity
Signed-off-by: S Davis <myriagon@sddw.net>
=> Fix typos and make minor tweaks to punctuation and wording for clarity

.travis.yml, setup.cfg, setup.py
* Also change __version__ import to allow it to be run from anywhere
* Address Issue #34
=> Update setup.py to reflect new project structure.

dimod/binary_quadratic_model.py, dimod/classes/sampler.py, dimod/decorators.py, dimod/reference/samplers/exact_solver.py, dimod/response.py, tests/test_binary_quadratic_model.py, tests/test_response.py
* Update change_vartype and relabel_variables in both Response and BinaryQuadraticModel.
* Change vartype input checking to use the decorator in a few places.
* Finally make sure that the vartype checking decorator also checks the kwargs.
=> Change kwarg copy to inplace

dimod/classes/__init__.py, dimod/classes/composite.py, dimod/classes/sampler.py, dimod/classes/structured.py, dimod/decorators.py, dimod/exceptions.py, dimod/reference/composites/__init__.py, dimod/reference/composites/spin_transform.py, dimod/reference/composites/structure.py, dimod/test/composite_api.py, dimod/test/sampler_api.py, tests/test_spin_transform.py, tests/test_structure_composite.py, tests/test_structured.py
* Adds a new Structured base class that can be inherited by Samplers and Composed Samplers
* Separate the Composite and Sampler base classes.
There are many todos still. These will be filled in with subsequent testing
=> Structured sampler

dimod/binary_quadratic_model.py, dimod/decorators.py, dimod/response.py
It now accepts a list of argument names which are to be constrained.
=> Refactor `vartype_argument` decorator

dimod/binary_quadratic_model_convert.py, dimod/core/composite.py, dimod/core/structured.py, dimod/test/composite_api.py, dimod/test/sampler_api.py, docs/Makefile, tests/test_exact_solver.py, tests/test_random_sampler.py, tests/test_simulated_annealing.py, tests/test_spin_transform.py, tests/test_structure_composite.py, tests/test_structured.py
Including: mutable args, `object` inheritance, test mixins.
=> Fix several potential issues

dimod/vartypes.py, docs/reference/exceptions.rst, docs/reference/index.rst, docs/reference/response.rst, docs/reference/utilities.rst, docs/reference/vartypes.rst
=> Doc skeleton

dimod/compatibility23.py, dimod/decorators.py
=> Add getargspec to compatibility23.py

dimod/binary_quadratic_model.py
@arcondello PR so I can fetch your updated master. Please see that "quadratic (dict[(variable, variable), bias]):" renders correctly, in my local build it renders incompletely: "dict[(variable, variable – The quadratic biases as a dict."
=> Update docstring, example of BQM() class

README.rst, docs/index.rst
@arcondello a first draft so there's something for now and to get started with this repo
=> Update homepage (placeholder)

dimod/binary_quadratic_model.py
@arcondello, note that I also specified variables & offset as being added
=> Update the update method

dimod/binary_quadratic_model.py
=> Update docstrings, examples for add_* methods

dimod/binary_quadratic_model.py
@arcondello review this one more carefully please.
=> Update docstring, example for Vartype Properties

dimod/utilities.py
@arcondello, please review carefully, I added and changed content. I'll return to this one for an edit later, just wanted content in place for this round. Thanks!
=> Add content for utilities

dimod/binary_quadratic_model.py, dimod/compatibility23.py, dimod/core/composite.py, dimod/core/sampler.py, dimod/core/structured.py, dimod/decorators.py, dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/simulated_annealing.py, dimod/response.py, dimod/utilities.py, requirements.txt, requirements_test.txt, setup.py
=> Replace compatibility23.py with six

requirements.txt, setup.py
http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies
=> Add commas before upper bounds on versions

dimod/response.py, tests/test_response.py
=> Update Response.from_futures to resolve on response read

.travis.yml
=> Change 'brew install python3' to 'brew upgrade python'

README.rst, dimod/binary_quadratic_model.py, dimod/core/sampler.py, dimod/core/structured.py, dimod/utilities.py
=> Fix existing docstrings

dimod/binary_quadratic_model.py
=> Fix rendering problem of dimod.BinaryQuadraticModel.binary in RtD

dimod/core/sampler.py, docs/reference/samplers.rst
@arcondello please review the new examples I added to Mixin Methods
=> Update Sampler class & overview content

docs/reference/introduction.rst
@arcondello, a placeholder to start off on adding content for Reference Documentation / Introduction. Might be worth merging to help other get get started on adding more content here. Otherwise I'll work on this more when I'm back.
=> Add first-draft content for References/Intro

dimod/core/structured.py
=> Update structured sampler

.gitignore, dimod/binary_quadratic_model.py
@arcondello: also for Issue #142
=> Update convert methods plus .gitignore for Sphinx /generated files

dimod/core/composite.py, docs/reference/samplers.rst
@arcondello For some of these examples I use pseudocode to not lengthen too much and rely on the reference examples for full implmentation
=> Update composed samplers & composites

dimod/__init__.py, dimod/embedding/chain_breaks.py, dimod/embedding/transforms.py, dimod/response.py, docs/reference/embedding.rst, tests/test_embedding.py
* _most_common now throws a ValueError for empty sequences
* _all_equal now correctly returns True for empty sequences
=> Address edge cases for embedding utility functions

dimod/binary_quadratic_model.py, dimod/embedding/transforms.py, tests/test_binary_quadratic_model.py
=> Issues #170 and #169

dimod/embedding/chain_breaks.py
Fix for https://github.com/dwavesystems/dimod/issues/179
=> Fix weighted_random's random.choice(vals)

dimod/embedding/transforms.py, dimod/response.py, docs/reference/response.rst
@arcondello will continue on this after the demo2 work, but might as well merge earlier
=> Updates to Response, Embedding (partial), mostly to expand doctest coverage

dimod/reference/composites/spin_transform.py, dimod/reference/composites/structure.py, dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, docs/reference/index.rst, docs/reference/ref_samplers_composites.rst
@arcondello some time in the future I'll probably do a 2nd pass on this like I'm doing on the rest of dimod but I'd like to merge it, it's useful content, especially for new users
=> Add reference samplers & composites

dimod/embedding/chain_breaks.py, dimod/embedding/utils.py, dimod/utilities.py
@arcondello some last minor clean-ups from round 2
=> Update utilities, chains

dimod/abc.py, dimod/core/composite.py, dimod/core/sampler.py, dimod/core/structured.py, dimod/meta.py
Closes #200
Needs testing to determine if it addresses #199
=> Sampler ABC fix

dimod/testing/asserts.py, docs/Makefile, docs/reference/index.rst, docs/reference/testing.rst, tests/test_exact_solver.py, tests/test_random_sampler.py
=> Improve dimod.testing submodule

dimod/response.py, tests/test_response.py
=> Fix Response.done()

dimod/response.py
=> Address pandas FutureWarning

dimod/decorators.py
=> Add missing import to dimod/decorators

dimod/io/json.py
=> Correct order of quadratic bias labels in BQM JSON encoding

requirements.txt, setup.py
=> Install enum34 only for <3.3

dimod/binary_quadratic_model.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py
=> Add OrderedBinaryQuadraticModel

dimod/embedding/transforms.py, tests/test_embedding_transforms.py
=> Fix unembed_response for embeddings larger than the source bqm

dimod/binary_quadratic_model.py, dimod/io/coo.py, tests/test_io_coo.py
=> Add support for headers in BQM COO methods

dimod/decorators.py, dimod/generators/random.py
=> Address some issues introduced in generator code

dimod/sampleset.py, tests/test_sampleset.py
=> Fix missing import in sampleset.py

dimod/sampleset.py, tests/test_sampleset.py
=> Allow empty samples for SampleSet

dimod/binary_quadratic_model.py, dimod/reference/composites/spin_transform.py, dimod/reference/composites/structure.py, dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, dimod/sampleset.py, docs/reference/ref_samplers_composites.rst, docs/reference/response.rst, docs/reference/sampleset.rst
@arcondello I'll break this into parts to keep PR sizes tolerable
=> Update bqm, samplers/composites, sampleset

dimod/binary_quadratic_model.py, tests/test_binary_quadratic_model.py
=> Allow interactions/variables to be excluded when scaling bqms

dimod/io/bson.py
The variable size restriction was to keep the index dtype consistent, but it's pretty easy to select which dtype should be used.
There was also an error in the formula for calculating the linear index that only happened at larger problem sizes.
=> Fix complete indexing in bson serialization and remove <= 2^16 variable restriction

dimod/decorators.py
=> Index labelled input decorator

dimod/views.py
We lose the ability to store per-bias data but we save about 20% of memory when biases are floats and we copy about twice as fast relative to #324 .
On the other hand we store two copies of the biases when they are immutable.
=> Store the biases directly

dimod/binary_quadratic_model.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py
=> Add BinaryQuadraticModel.fix_variables

dimod/embedding/transforms.py, tests/test_embedding_transforms.py
=> Add smear_vartype to embed_bqm function.

dimod/sampleset.py, tests/test_sampleset.py
=> Add SampleSet.to_pandas_dataframe method

dimod/reference/composites/__init__.py, dimod/reference/composites/fixedvariable.py, docs/reference/ref_samplers_composites.rst, tests/test_fixedvariablecomposite.py
=> Add FixedVariableComposite

dimod/__init__.py, dimod/sampleset.py, docs/reference/sampleset.rst, tests/test_sampleset.py
* Add `concatenate` function for SampleSets, closes #349 
* Add `SampleSet.aggregate` method, closes #268 
* Add `SampleSet.from_samples_bqm` constructor
=> SampleSet utilities

dimod/binary_quadratic_model.py
Comparison from 0.8.1 to this commit
```
[e8726c36]       [6e5010f2]
44.1±20μs       32.6±0.7μs    ~0.74  bench_binary_quadratic_model.Construction.time_empty
-        24.8±4ms       12.5±0.2ms     0.50  bench_binary_quadratic_model.Construction.time_k100
-         211±6ms          112±2ms     0.53  bench_binary_quadratic_model.ConstructionVeryLarge.time_J15000
-      24.5±0.4ms       14.9±0.6ms     0.61  bench_binary_quadratic_model.Copy.time_k100
```
=> Speed up BQM.add_variable and BQM.add_interaction

dimod/__init__.py, dimod/binary_quadratic_model.py, dimod/sampleset.py, docs/reference/binary_quadratic_model.rst, tests/test_sampleset.py
Closes #365 
Closes #363 
Closes #364 
Add `BQM` as an alias for `BinaryQuadraticModel`
=> Misc fixes and features

dimod/__init__.py, dimod/sampleset.py, dimod/serialization/format.py, tests/test_serialization_format.py
The code is not complete, it needs a refactor, but I wanted to get early feedback. Right now it looks like:
```
>>> sampleset = dimod.RandomSampler().sample_ising({v: .3 for v in range(10)}, {}, num_reads=20) 
>>> print(sampleset)
0   1   2   3   4   5   6  ..   9               energy  num_occurrences
0   -1  +1  +1  -1  -1  -1  -1  ..  +1                 -1.2                1
1   +1  +1  -1  +1  -1  -1  -1  ..  -1                 -1.2                1
2   -1  +1  +1  +1  -1  -1  -1  ..  -1                 -1.2                1
3   -1  +1  +1  +1  -1  -1  -1  ..  -1                 -0.6                1
4   +1  +1  -1  +1  -1  -1  -1  ..  +1  -0.5999999999999999                1
5   -1  -1  -1  -1  -1  +1  -1  ..  +1  -0.5999999999999999                1
6   -1  -1  +1  +1  -1  -1  -1  .. …
```
=> SampleSet.__str__

dimod/higherorder.py, dimod/reference/composites/__init__.py, dimod/reference/composites/higherordercomposite.py, dimod/reference/composites/scalecomposite.py, docs/reference/ref_samplers_composites.rst, tests/test_scalecomposite.py
a composite to scale variables/interactions/offset of a problem.
Closes https://github.com/dwavesystems/dwave-system/issues/1
=> ScaleComposite

dimod/core/sampler.py, tests/test_sampler.py
=> Don't change vartype of bqm unnecessarily

dimod/sampleset.py, docs/reference/sampleset.rst, tests/test_sampleset.py
=> Add SampleSet.truncate method

dimod/binary_quadratic_model.py, dimod/serialization/bson.py, tests/test_binary_quadratic_model.py, tests/test_serialization_bson.py
=> Bson serialization bug fixes2

dimod/views.py, tests/test_binary_quadratic_model.py
=> Support pickling BQMs

dimod/higherorder.py, dimod/reference/composites/spin_transform.py, setup.py
Some functions did not work in numpy 1.14
Closes #388
=> Require numpy 1.15 and support 1.16

dimod/reference/composites/spin_transform.py
=> Fix SpinReversalTransform to correctly apply spin reversals

dimod/sampleset.py, dimod/serialization/format.py, tests/test_serialization_format.py
Closes #378 
Closes #411 
Still needs docs and tests.
=> SampleSet print refactor

dimod/reference/composites/higherordercomposites.py, dimod/testing/asserts.py, docs/reference/higherorder.rst, tests/test_polytruncatecomposite.py
=> Add PolyTruncateComposite

dimod/decorators.py, dimod/generators/chimera.py, dimod/generators/fcl.py, dimod/generators/random.py, tests/test_decorators.py, tests/test_generators.py
=> QOL improvements for BQM generators

dimod/generators/__init__.py, dimod/generators/constraints.py, tests/test_generators.py
Creates a bqm that is minimized when k of n variables are equal to 1.
Note that the function has not been added to the online documentation, see #433.
=> Add k-combinations generator

.circleci/config.yml, dimod/binary_quadratic_model.py, dimod/core/structured.py, dimod/higherorder/polynomial.py, dimod/reference/composites/spin_transform.py, dimod/sampleset.py, docs/reference/binary_quadratic_model.rst, docs/reference/higherorder.rst, docs/reference/ref_samplers_composites.rst
* Install boost in test-doctest for circle-ci. Closes #408 
* Build the docs before running the doctest in test-doctest
* Fix broken docstring examples. Closes #401 
* Add `BQM.normalize` to docs. Closes #434
=> Documentation fixes

dimod/binary_quadratic_model.py, dimod/core/composite.py, dimod/core/polysampler.py, dimod/core/sampler.py, dimod/core/structured.py, dimod/reference/composites/__init__.py, dimod/reference/composites/fixedvariable.py, dimod/reference/composites/roofduality.py, dimod/reference/composites/scalecomposite.py, dimod/reference/composites/spin_transform.py, dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, docs/reference/ref_samplers_composites.rst, docs/reference/samplers.rst
Refactor the online documentation for samplers and composites.
=> Refactor the Sampler/Composite docs

dimod/binary_quadratic_model.py, dimod/sampleset.py, dimod/views/bqm.py, dimod/views/samples.py, setup.py
Originally the first commit of #439 , need it for other work so separating it out
=> Make dimod.views a subpackage

dimod/sampleset.py, dimod/variables.py, dimod/views/samples.py, tests/test_sampleset.py, tests/test_variables.py, tests/test_views.py
=> Make SampleSet.samples return an iterable

dimod/binary_quadratic_model.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py
=> Add BQM.from_networkx_graph

dimod/reference/composites/fixedvariable.py, dimod/sampleset.py, docs/reference/sampleset.rst, tests/test_fixedvariablecomposite.py, tests/test_sampleset.py
Also update `FixedVariableComposite` to make use of the new method.
=> SampleSet.append method

dimod/sampleset.py, tests/test_sampleset.py
Fixes #458. Also add unit test for SampleSet with tuple variables.
=> Fix tuple variables for SampleSet deserialization

dimod/sampleset.py, tests/test_sampleset.py
=> Add sampleset slice

dimod/variables.py, tests/test_variables.py
=> Variables.relabel ignores unknown labels

dimod/binary_quadratic_model.py
=> Return a keyview for BQM.variables in python2

dimod/__init__.py, dimod/decorators.py, dimod/vartypes.py, docs/reference/vartypes.rst
=> Add as_vartype function

dimod/generators/random.py
Bug fix. Once this is in, PR #472 should pass Circle tests.
=> Fix length of quadratic

dimod/sampleset.py, dimod/variables.py, tests/test_sampleset.py
=> Support pickling sample sets

docs/reference/sampleset.rst
Add `SampleSet.resolve` method introduced in #478 to the docs
=> Add SampleSet.resolve to docs

dimod/reference/samplers/__init__.py, dimod/reference/samplers/null_sampler.py, docs/reference/ref_samplers_composites.rst, tests/test_null_sampler.py
Addresses one of the feature requests in #481
=> Add NullSampler

dimod/reference/composites/__init__.py, dimod/reference/composites/tracking.py, docs/reference/ref_samplers_composites.rst, tests/test_trackingcomposite.py
=> Add TrackingComposite

dimod/core/structured.py, dimod/utilities.py, docs/reference/utilities.rst, tests/test_utilities.py
This partly addresses #487, the EmbeddingComposite and similar will need to be updated to use `child_structure_dfs`.
See also #111
=> Add child_structure_dfs function

dimod/reference/composites/higherordercomposites.py, tests/test_higherordercomposite.py
Addresses the higher order composite as mentioned in #483 . Follows the pattern introduced in https://github.com/dwavesystems/dwave-system/pull/96. Creating a more general pattern is covered by #491.
=> Support initial_state kwarg in HigherOrderComposite

dimod/sampleset.py, tests/test_sampleset.py
=> Fix num_occurences in SampleSet.aggregate

dimod/binary_quadratic_model.py
=> Bug fix energy calculation when offset is not a float/int

dimod/roof_duality/_fix_variables.pyx, dimod/roof_duality/src/fix_variables.cpp, dimod/roof_duality/src/fix_variables.hpp
The exception changes from #516
=> Minor changes to cython for roof duality

.appveyor.yml, .appveyor/install.ps1, .appveyor/run_with_env.cmd, dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h
Using the scripts from https://github.com/dwavesystems/dwave-tabu/pull/15 and https://github.com/dwavesystems/dwave-tabu/pull/13, try to fix the build on windows.
Still need to change the actual c++ code to be compliant.
=> Refactor appveyor config

dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjmapbqm.pxd, dimod/bqm/adjmapbqm.pyx, dimod/bqm/cppbqm.pxd, dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h, tests/test_adjarraybqm.py, tests/test_adjmapbqm.py
There was as big impact on performance that will need to be mitigated
=> Arbitrary variables labels in AdjArrayBQM and AdjMapBQM

dimod/binary_quadratic_model.py, dimod/utilities.py, tests/test_binary_quadratic_model.py
=> Make BQM able to be deep copied when not writeable

dimod/bqm/adjvectorbqm.pxd, dimod/bqm/adjvectorbqm.pyx, dimod/bqm/cppbqm.pxd, dimod/bqm/src/adjmap.h, dimod/bqm/src/adjvector.cc, dimod/bqm/src/adjvector.h, setup.py, tests/test_adjarraybqm.py, tests/test_adjmapbqm.py, tests/test_adjvectorbqm.py, tests/test_bqm.py
Includes the commits from and therefore closes #523
=> Add AdjVectorBQM

dimod/__init__.py, dimod/bqm/__init__.py, dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/adjmapbqm.pxd, dimod/bqm/adjmapbqm.pyx, dimod/bqm/adjvectorbqm.pxd, dimod/bqm/adjvectorbqm.pyx, dimod/core/bqm.py, docs/reference/bqm/index.rst, docs/reference/bqm/sparse.rst, tests/test_adjarraybqm.py, tests/test_adjdictbqm.py, tests/test_adjmapbqm.py, tests/test_adjvectorbqm.py, tests/test_bqm.py
This is still obviously very much a work in progress - documentation and tests are incomplete.
=> Add ABC for cyBQMs and reference dict implementation

dimod/higherorder/utils.py, tests/test_higherorder.py
Make quadratic handles square terms correctly now. Bug report came from https://support.dwavesys.com/hc/en-us/community/posts/360035719954-dimod-make-quadratic-returns-error
=> Fix make_quadratic bug

dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/adjmapbqm.pyx, dimod/bqm/adjvectorbqm.pyx, dimod/bqm/cppbqm.pxd, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h, dimod/bqm/src/adjvector.cc, dimod/bqm/src/adjvector.h, dimod/core/bqm.py, dimod/views/bqm.py, tests/test_bqm.py
There is a lot of duplicated code between `adjmapbqm.pyx` and `adjvectorbqm.pyx`. This will need to be addressed in a later PR.
=> Add cybqm adjacency, linear, and quadratic views

dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h, dimod/bqm/src/adjvector.h
Follows google style guide https://google.github.io/styleguide/cppguide.html#Namespaces
=> Don't indent in namespace in c++ code

dimod/higherorder/utils.py, tests/test_higherorder.py
=> Change make_quadratic to use a loop rather than recursion

.circleci/config.yml, requirements.txt
=> Add windows support in circle-ci

dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/adjmapbqm.pxd, dimod/bqm/adjvectorbqm.pxd, dimod/bqm/common.pxd, dimod/bqm/common.pyx, dimod/bqm/cppbqm.pxd, dimod/bqm/shapeablebqm.pyx.src, dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h, dimod/bqm/src/adjvector.cc, dimod/bqm/src/adjvector.h, dimod/core/bqm.py, dimod/serialization/fileview.py, setup.py, tests/test_bqm.py, tests/test_serialization_fileview.py
=> File-like access to experimental BQMs

.circleci/config.yml
Based on (read: copy :smile: ) https://github.com/dwavesystems/dwave-tabu/pull/53
=> Force (lie about) macOS 10.9 binary compatibility

tests/test_bqm.py
Wrote some based on an erroneous bug report. But they are still worth having.
=> Add 1-variable tests for cyBQM construction

dimod/binary_quadratic_model.py, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/shapeablebqm.pyx.src, dimod/bqm/utils.pyx, dimod/core/bqm.py, dimod/higherorder/polynomial.py, dimod/utilities.py, dimod/variables.py, tests/test_bqm.py
Closes #395 , though with a function not a decorator
=> Refactor relabelling

.circleci/config.yml, setup.py
=> Turn off FH4 exception handling

dimod/__init__.py, dimod/binary_quadratic_model.py, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/shapeablebqm.pyx.src, dimod/converters.py, dimod/core/bqm.py, dimod/serialization/coo.py, setup.py, tests/test_binary_quadratic_model.py, tests/test_bqm.py
Going through the Ocean packages and finding/fixing bugs as necessary
=> 0.9.0 integration fixes

dimod/core/sampler.py, dimod/sampleset.py, tests/test_sampler.py, tests/test_sampleset.py
Addresses the worst offenders for #430
=> Make SampleSet.change_variable and sampler mixin methods non-blocking

docs/introduction.rst, docs/reference/bqm.rst, docs/reference/sampleset.rst
Removes duplicate content post dwavesystems/dwave-ocean-sdk#62
Assumes we agree on proposed structure; alternative is for content to live here and be pulled into SDK top level.
NOT TO BE MERGED BEFORE 62.
=> (Awaiting SDK update) Integrate SDK concepts locally

.circleci/config.yml, .gitignore, setup.py, tests/test_cppbqm.pyx
Can now do `python setup.py build_ext --inplace --build-tests` to build any tests written in cython
=> Support tests written in cython

dimod/reference/composites/scalecomposite.py, tests/test_scalecomposite.py
=> remove scaling information from the bqm object

dimod/bqm/adjdictbqm.py, dimod/core/bqm.py, dimod/core/composite.py, dimod/core/sampler.py, dimod/core/structured.py, dimod/generators/constraints.py, dimod/generators/random.py, dimod/higherorder/polynomial.py, dimod/higherorder/utils.py, dimod/reference/composites/clipcomposite.py, dimod/reference/composites/connectedcomponent.py, dimod/reference/composites/fixedvariable.py, dimod/reference/composites/higherordercomposites.py, dimod/reference/composites/roofduality.py, dimod/reference/composites/scalecomposite.py, dimod/reference/composites/spin_transform.py, dimod/reference/composites/structure.py, dimod/reference/composites/truncatecomposite.py, dimod/reference/samplers/exact_solver.py, dimod/sampleset.py, dimod/traversal.py
@arcondello, we can see just before SDK release whether to merge or leave till next time. I'll still be working on this tomorrow morning.
=> Expand doctest coverage & update examples (part 1)

dimod/binary_quadratic_model.py, dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/null_sampler.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, dimod/sampleset.py, dimod/serialization/coo.py, dimod/serialization/utils.py, dimod/utilities.py, docs/introduction.rst, docs/reference/sampler_composites/higher_order_samplers.rst, docs/reference/sampler_composites/index.rst, docs/reference/sampler_composites/samplers.rst
Just to complete https://github.com/dwavesystems/dimod/pull/638. I would still like to go through this repo more thoroughly, but in the meanwhile this at least gets almost all the examples tested. 
It also add higher order samplers to RTD.
=> Expand doctest coverage & update examples (part 2) 

dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/shapeablebqm.pyx.src, dimod/core/bqm.py, tests/test_bqm.py
=> Make cybqms pickleable and deepcopyable

.circleci/config.yml
Numpy does not have 3.9 wheels yet to manylinux deploy fails for 3.9.
=> Don't deploy for python 3.9 (yet)

dimod/core/bqm.py, tests/test_bqm.py
=> Fix VartypeView.relabel_variables

dimod/core/bqm.py, tests/test_bqm.py
=> fixes #697, fixed relabel variables as integers with no inplace

dimod/bqm/adjarraybqm.pyx, dimod/bqm/shapeablebqm.pyx.src, docs/reference/bqm_classes/adjarraybqm.rst, docs/reference/bqm_classes/adjmapbqm.rst, docs/reference/bqm_classes/adjvectorbqm.rst, tests/test_bqm.py
=> Add BQM.to_file and BQM.from_file for supported BQM types

.gitignore, dimod/__init__.py, dimod/bqm/cppbqm.pxd, dimod/discrete/__init__.py, dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, dimod/include/dimod/adjarraybqm.h, dimod/include/dimod/adjmapbqm.h, dimod/include/dimod/adjvectorbqm.h, dimod/include/dimod/utils.h, docs/reference/dqm.rst, docs/reference/index.rst, setup.py, tests/test_discrete_quadratic_model.py, testscpp/tests/test_bqm.cpp
Added a parallelized AdjVectorBQM constructor from dense matrix.
This constructor requires the source matrix to be not read-only.
=> Parallelized AdjVectorBQM constructor using dense matrix

dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, docs/reference/dqm.rst, tests/test_discrete_quadratic_model.py
Closes #712 and other misc bugs.
Unfortunately does not address #714 (yet)
=> Misc DQM Improvements

dimod/serialization/format.py, tests/test_serialization_format.py
=> Support printing DISCRETE sample sets

dimod/include/dimod/adjmapbqm.h, testscpp/Makefile
Parallelized AdjMapBQM constructor from dense array. 
Added testing of cpp files with openmp.
=> Parallelized AdjMapBQM constructor from dense array

dimod/discrete/discrete_quadratic_model.py
Part of https://github.com/dwavesystems/dwave-system/pull/356
=> Deprecate ``compressed`` in DQM

docs/index.rst, docs/reference/index.rst
See https://github.com/dwavesystems/dwave-ocean-sdk/issues/56
=> Remove release version from docs

dimod/__init__.py, dimod/reference/composites/connectedcomponent.py, dimod/reference/composites/fixedvariable.py, dimod/reference/composites/higherordercomposites.py, dimod/sampleset.py, docs/reference/sampleset.rst, tests/test_sampleset.py
- Helps to improve [this PR](https://github.com/dwavesystems/dwave-system/pull/359)
Closes #738
=> Add append_data_vectors() to SampleSet

setup.py
See https://github.com/dwavesystems/dimod/pull/734#discussion_r506533860
=> Use default c++ with MSVC

.circleci/config.yml
=> Minor circle-ci config changes

dimod/binary_quadratic_model.py, dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/adjmapbqm.pxd, dimod/bqm/adjvectorbqm.pxd, dimod/bqm/shapeablebqm.pyx.src, dimod/core/bqm.py, dimod/generators/constraints.py, dimod/serialization/coo.py, dimod/utilities.py, docs/reference/bqm.rst, docs/reference/bqm_classes/adjdictbqm.rst, docs/reference/bqm_classes/adjmapbqm.rst, docs/reference/bqm_classes/adjvectorbqm.rst
@arcondello, if you're releasing a new dimod today we can merge early.
=> Add missing BQM methods' docstrings

dimod/core/bqm.py, tests/test_bqm.py
Closes https://github.com/dwavesystems/dimod/issues/740
=> Fix BQM.from_numpy_vectors variable order in py35

dimod/generators/__init__.py, dimod/generators/chimera.py, dimod/generators/random.py, tests/test_generators.py
Generator for random BQMs. Will be performant once https://github.com/dwavesystems/dimod/issues/653 is implemented.
=> Add gnp_random_bqm function for generating random BQMs

dimod/bqm/adjdictbqm.py, tests/test_bqm.py
=> Fix bias type in AdjDictBQM constructed from ndarray

dimod/sampleset.py, dimod/serialization/format.py, tests/test_serialization_format.py
Closes https://github.com/dwavesystems/dimod/issues/758
I really want to just chuck and rewrite that entire file, but just fixing the bug for now.
=> Fix misaligned energy values in printed sampleset

dimod/discrete/cydiscrete_quadratic_model.pyx, tests/test_discrete_quadratic_model.py
Closes https://github.com/dwavesystems/dimod/issues/761
=> Disallow quadratic interaction between cases of a variable

dimod/core/polysampler.py, dimod/higherorder/utils.py, dimod/reference/composites/higherordercomposites.py, dimod/testing/asserts.py, dimod/views/samples.py, tests/test_binary_quadratic_model.py, tests/test_discrete_quadratic_model.py, tests/test_exact_solver.py, tests/test_higherorder.py, tests/test_higherordercomposite.py, tests/test_polytruncatecomposite.py, tests/test_sampleset.py, tests/test_traversal.py
See https://github.com/dwavesystems/dwave-system/issues/374
=> Fix deprecation warnings

dimod/discrete/discrete_quadratic_model.py, dimod/reference/composites/higherordercomposites.py, dimod/sampleset.py, dimod/variables.py, dimod/views/samples.py, tests/test_variables.py
This does not address https://github.com/dwavesystems/dimod/issues/612 (yet), but is a first step.
=> Combine SampleSet's and DQM's variables objects

dimod/variables.py, tests/test_discrete_quadratic_model.py, tests/test_variables.py
=> Fix handling of integer-valued floats in Variables

dimod/discrete/cydiscrete_quadratic_model.pyx, tests/test_discrete_quadratic_model.py
=> Fix cyDQM dtype setting

dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, docs/reference/dqm.rst, tests/test_discrete_quadratic_model.py
See https://github.com/dwavesystems/dimod/pull/784#issuecomment-769264502
=> Rename DQM.add_constraint_as_quadratic to DQM.add_linear_equality_constraint

dimod/cyvariables.pxd, dimod/cyvariables.pyx
Add `cdef` equivalents for `__len__` and `__getitem__` in `cyVariables`.
=> Add cyVariables.size() and .at(..)

docs/conf.py
Fixes error 
```
Exception occurred:
File "/home/circleci/repo/docs/conf.py", line 139, in setup
app.add_stylesheet('cookie_notice.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```
=> Update cookie methods in conf.py

dimod/include/dimod/quadratic_model.h, testscpp/tests/test_quadratic_model.cpp
For neighborhood iterators:
* Made them random access
* Move them out from being nested in Neighborhood
* Fix warnings generated from empty constructor
* Implement operator->()
Also added a new quadratic bias iterator.
=> Refactor c++ iterators

dimod/binary/binary_quadratic_model.py, dimod/constrained.py, dimod/discrete/discrete_quadratic_model.py, dimod/serialization/fileview.py
See also: https://github.com/dwavesystems/dimod/pull/839/files#r650208852
=> Add make_header, read_header and write_header functions

docs/conf.py, docs/index.rst, docs/release_notes.rst, docs/requirements.txt, releasenotes/notes/add-reno-b77e7f0bad41e5b2.yaml, requirements.txt
Uses default setting for now, until we get some more experience with it.
=> Begin using Reno

pyproject.toml, requirements.txt
=> Increase lower bound on setuptools

dimod/typing.py, dimod/vartypes.py, releasenotes/notes/integer-vartype-371d5f7eb9b6c0a3.yaml, tests/test_serialization_format.py
Closes https://github.com/dwavesystems/dimod/issues/664
=> Add Vartype.INTEGER

dimod/binary/binary_quadratic_model.py, dimod/views/quadratic.py, tests/test_bqm.py
Can be used in the upcoming `QuadraticModel` implementation.
I don't think any of these changes are user-facing enough to be worth adding to the changelog.
=> Add `dimod.views.quadratic.QuadraticViewsMixin`

dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, dimod/serialization/fileview.py, tests/test_quadratic_model.py
Incorporates the suggestion from https://github.com/dwavesystems/dimod/issues/660 and uses local headers. We can consider using this format in BQM in the future as well.
=> Add QM serialization

.circleci/config.yml, setup.py
=> Remove support for numpy 1.21.0 and 1.21.1 due to typing bug

dimod/constrained.py, dimod/discrete/discrete_quadratic_model.py, docs/reference/constrained.rst, docs/reference/dqm.rst, releasenotes/notes/DQM.get_cases-5a0d84176c5b07ac.yaml, releasenotes/notes/cqm-from-bqm-dqm-qm-707a871f0f3ac79a.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/866
=> Add `CQM.from_bqm`, `CQM.from_dqm` and `CQM.from_qm`

dimod/constrained.py, releasenotes/notes/fix-integer-bounds-in-constraint-by-terms-70f2f19c85ecc2e6.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/943
=> Fix adding integer variables with bounds via `CQM.add_constraint_from_iterable`

dimod/binary/binary_quadratic_model.py, dimod/constrained.py, dimod/decorators.py, dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, dimod/utilities.py, docs/reference/constrained.rst, docs/reference/quadratic.rst, releasenotes/notes/add-QM.remove_interaction-e97a7ac91db2e2b8.yaml, releasenotes/notes/feature-CQM.substitute_self_loops-eb5a4952ee2a460a.yaml, tests/test_bqm.py, tests/test_constrained.py, tests/test_quadratic_model.py
Also some other misc bug fixes.
=> Add `CQM.substitute_self_loops` method

dimod/binary/binary_quadratic_model.py, docs/reference/quadratic.rst
First draft just to complete the one liners and make some fixes, will expand in another PR.
=> Complete BQM one-liners

dimod/generators/__init__.py, dimod/generators/gates.py, docs/reference/quadratic.rst, releasenotes/notes/gate-generators-43208669a09df0d8.yaml, tests/test_generators.py
Closes https://github.com/dwavesystems/dimod/issues/951
=> Add logic gates to generators

dimod/generators/__init__.py, dimod/generators/integer.py, docs/reference/quadratic.rst, releasenotes/notes/binary-encoding-generator-82b1cfb9fd0e571a.yaml, tests/test_generators.py
Prerequisite feature for https://github.com/dwavesystems/dimod/issues/959
=> Add binery_encoding generator

dimod/constrained.py, releasenotes/notes/inverter-json-44f8d5caa74cf335.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/977
=> Add CQMToBQMInverter.to_dict() and .from_dict()

docs/conf.py
Backport #822 from main (0.10.x) to 0.9.x.
=> Backport fix for Sphinx 4

.circleci/config.yml, requirements.txt
Backport 5fa47d369292c67f8d012b695d8d3687b8719883 from main to 0.9.x.
=> Backport py35 support removal

dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/include/dimod/quadratic_model.h, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, releasenotes/notes/energy-overflow-96da0e98ff312f5e.yaml, tests/test_quadratic_model.py, testscpp/tests/test_quadratic_model.cpp
Closes https://github.com/dwavesystems/dimod/issues/982
=> Fix energy calculations for large integer values

dimod/binary/binary_quadratic_model.py, dimod/generators/anti_crossing.py, dimod/generators/binpacking.py, dimod/generators/chimera.py, dimod/generators/constraints.py, dimod/generators/fcl.py, dimod/generators/knapsack.py, dimod/generators/multi_knapsack.py, dimod/generators/random.py, dimod/typing.py, docs/reference/constrained.rst, docs/reference/generators.rst, docs/reference/index.rst, docs/reference/quadratic.rst, releasenotes/notes/anticluster-0881102aef3dee9e.yaml, releasenotes/notes/deprecate-bin-packing-9072d578f0c872f3.yaml, releasenotes/notes/knapsack-refresh-8c621806266ef64b.yaml, tests/test_generators.py
Refresh the generators docs and some of the docstrings/typo annotations.
=> Generators refresh

MANIFEST.in, releasenotes/notes/pep561-787ed095184563d0.yaml
Closes https://github.com/dwavesystems/dimod/issues/980
=> Make dimod PEP 561 compatible

dimod/binary/binary_quadratic_model.py, dimod/quadratic/quadratic_model.py, releasenotes/notes/div-and-pow-9bc4810c5acae0ba.yaml, tests/test_bqm.py, tests/test_quadratic_model.py
Closes https://github.com/dwavesystems/dimod/issues/864
Closes https://github.com/dwavesystems/dimod/issues/984
=> Allow BQM and QM to be squared or divided by a number

dimod/quadratic/quadratic_model.py
=> removed discrete variables in the docstring

dimod/constrained.py, docs/reference/constrained.rst, releasenotes/notes/cqm-constraint-data-c8217056d499f800.yaml, releasenotes/notes/cqm.check_feasible-6615c7967181f478.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/971
Closes https://github.com/dwavesystems/dimod/issues/975 as redundant
=> Add CQM.iter_constraint_data, CQM.iter_violations and CQM.violations

docs/reference/cpp.rst
Part of https://github.com/dwavesystems/dwave-ocean-sdk/pull/153
=> Add CPP docs to SDK build

dimod/binary/binary_quadratic_model.py, dimod/constrained.py, dimod/quadratic/quadratic_model.py, docs/reference/constrained.rst, docs/reference/quadratic.rst, releasenotes/notes/CQM.is_equal-0417b371550836e5.yaml, releasenotes/notes/QM.is_almost_equal-74c6c997d8b454b2.yaml, tests/test_bqm.py, tests/test_constrained.py, tests/test_quadratic_model.py
=> CQM equality methods

dimod/higherorder/__init__.py, dimod/higherorder/utils.py, docs/reference/higherorder.rst, releasenotes/notes/reduce-binary-polynomial-71ae7d9a79fb0cf1.yaml, tests/test_higherorder.py
Factored out `reduce_terms` from `make_quadratic` to be used in creating CQM's from BinaryPolynomials.
Introduces more efficient algorithm for reducing polynomials
=> refactor & optimize make_quadratic

.circleci/config.yml, pyproject.toml, releasenotes/notes/py3.10-0ae76c2d6f57725f.yaml, requirements.txt, setup.py
=> Use cibuildwheel

dimod/sampleset.py, dimod/views/samples.py, docs/reference/sampleset.rst, releasenotes/notes/keep-drop-variables-0a7bb575e095bbbb.yaml, tests/test_sampleset.py
It simply removes variables from a sampleset
=> dropping variables from a sampleset

dimod/constrained.py, docs/reference/constrained.rst, releasenotes/notes/feature-cqm-relabel-variables-cc17797d4dfab53d.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/1011
=> Add CQM.relabel_variables method

dimod/decorators.py, releasenotes/notes/fix_bqm_structured_error-98a72320a8759168.yaml, tests/test_decorators.py
fixes the unit test in https://github.com/dwavesystems/dwave-hybrid/pull/256
```
python -m unittest dwave-ocean-sdk/dwave-hybrid/tests/test_samplers.py 
.........................
----------------------------------------------------------------------
Ran 25 tests in 1.675s
OK
```
=> Fix bqm_structured BinaryQuadraticModelStructureError error

dimod/binary/binary_quadratic_model.py, dimod/binary/vartypeview.py, dimod/views/quadratic.py, docs/reference/quadratic.rst, releasenotes/notes/fix-set-linear-set-quadratic-f0bae27b98a59bcb.yaml, releasenotes/notes/polystring-d6ef3f4ec287cbac.yaml, tests/test_bqm.py, tests/test_quadratic_model.py
~Todo: Quadratic model~
In the future we might consider using this as the default printing. Or at least allowing a global configuration to set that.
=> Add ability to print quadratic models as a polynomial

dimod/binary/binary_quadratic_model.py, dimod/quadratic/quadratic_model.py, releasenotes/notes/variable_array_feature-043bba2153ae6d4c.yaml, tests/test_bqm.py, tests/test_quadratic_model.py
Implement `BinaryArray`, `SpinArray`, and `IntegerArray` methods.
Each method builds a numpy object array from their respective variable generator methods.
Closes #1063
=> Implement `BinaryArray`, `SpinArray`, and `IntegerArray` methods.

dimod/generators/gates.py, releasenotes/notes/multiplication-circuit-carry-bugfix.yaml, tests/test_generators.py
Carry bit of the most significant column of a row need to feed add to the most significant column of the next row.
=> multiplication_circuit bugfix

dimod/constrained.py, dimod/exceptions.py, releasenotes/notes/CQM.fix_variable-cascade-15a810174ff69666.yaml, tests/test_constrained.py
See discussion in https://github.com/dwavesystems/dimod/pull/1083.
=> Add cascade keyword argument to CQM.fix_variable[s]()

dimod/constrained.py
...and instead just look through the existing discrete constraints.
This changes the complexity from O(1) to O(# of discrete constraints)
but that number will generally be low and this way we're not keeping
duplicated information that needs to be tracked.
If we later find this to be a performance bottleneck we can restore
it.
=> Remove CQM._discrete private attribute

dimod/constrained.py, docs/reference/constrained.rst, releasenotes/notes/QM.add_discrete-variations-cd171a3c755b1048.yaml, tests/test_constrained.py, tests/test_exact_solver.py
This does not go quite as far as https://github.com/dwavesystems/dimod/issues/921 but it does allow for closer syntax.
=> Support additional argument types in CQM.add_discrete()

dimod/binary/cybqm/cybqm_template.pxd.pxi, dimod/binary/cybqm/cybqm_template.pyx.pxi, releasenotes/notes/feature-BQM.resize-return-value-c0b8680d68d42ea6.yaml, tests/test_bqm.py
Previously it always returned 0.
Closes https://github.com/dwavesystems/dimod/issues/1091
=> Change BQM.resize() to return the size difference

dimod/sampleset.py, dimod/typing.py, releasenotes/notes/as-samples-refactor-589c726932e2a830.yaml, tests/test_sampleset.py
Needs a more serious docs pass.
Closes https://github.com/dwavesystems/dimod/issues/543
Closes https://github.com/dwavesystems/dimod/issues/1008
=> Refactor as_samples() and add SamplesLike to typing

dimod/constrained.py, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, docs/reference/constrained.rst, releasenotes/notes/non-integer-bounds-69ff82590aaaa83e.yaml, tests/test_constrained.py, tests/test_quadratic_model.py
Closes https://github.com/dwavesystems/dimod/issues/1105
=> Add CQM.set_upper_bound CQM.set_lower_bound methods

dimod/utilities.py, releasenotes/notes/variable-relabel-dup-target-324d1ba78ac71065.yaml, tests/test_variables.py
Closes https://github.com/dwavesystems/dimod/issues/1110
=> Fix relabelling two model variables to the same target

dimod/constrained.py, dimod/utilities.py, docs/reference/constrained.rst, releasenotes/notes/constraint-manipulation-05eb6e2a47b919d4.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/1066
Closes https://github.com/dwavesystems/dimod/issues/1104
=> Add constraint manipulation methods

dimod/constrained.py, dimod/quadratic/quadratic_model.py
Close https://github.com/dwavesystems/dimod/issues/1114
=> Replace i<=j for i<j in quadratic model definition

dimod/binary/binary_quadratic_model.py, dimod/binary/cybqm/cybqm_template.pxd.pxi, dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/binary/pybqm.py, dimod/binary/vartypeview.py, dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pxd.pxi, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, docs/reference/quadratic.rst, releasenotes/notes/nbytes-5bd096b1cde4e561.yaml, tests/test_bqm.py, tests/test_quadratic_model.py, testscpp/tests/test_quadratic_model.cpp
Closes https://github.com/dwavesystems/dimod/issues/668
=> Add QuadraticModel.nbytes() and BinaryQuadraticModel.nbytes() methods

dimod/sym.py, releasenotes/notes/comparison-printing-89ab51e3f4051d9c.yaml, tests/test_symbolic.py
See discussion in https://github.com/dwavesystems/dimod/pull/1117
=> Add better printing for `Comparison` objects

docs/intro/intro_symbolic_math.rst
Let me know your opinion on whether a last section with a CQM example is desirable, I'm vacillating on that
=> Update intro to symbolic

dimod/higherorder/polynomial.py, dimod/higherorder/utils.py, dimod/typing.py, docs/reference/higherorder.rst, releasenotes/notes/add_typing_polynomial-df4b35b09a72ebca.yaml
Current doctest failure is unrelated (``README.rst.rst: WARNING: broken link: https://img.shields.io/pypi/pyversions/dimod.svg``) and will probably resolve itself later
=> Refresh higher-order docstrings & add examples

dimod/include/dimod/quadratic_model.h, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, releasenotes/notes/fix-energy-squared-9b42a218928736b9.yaml, tests/test_quadratic_model.py, testscpp/tests/test_quadratic_model.cpp
Closes https://github.com/dwavesystems/dimod/issues/1136
=> Fix energy calculations for QMs with squared terms

dimod/typing.py, dimod/vartypes.py, docs/reference/index.rst, docs/reference/typing.rst, tests/requirements.txt, tests/test_typing.py, tests/typing/bias.pyi
There is more testing needed, but that will come in followup PRs. For now just putting the minimum amount in that's needed to check that the approach works
=> Add documentation and testing for `dimod.typing`

dimod/constrained.py
=> Fix docstring bug in cqm.cqm_to_bqm()

benchmarks/cqm.py, dimod/constrained.py, dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, releasenotes/notes/CQM.set_objective-speedup-05801899c467408d.yaml, tests/test_constrained.py, tests/test_quadratic_model.py
Provides a 60% speedup to `QM.update()` and `CQM.set_objective()`.
=> Improve the performance of QM.update()

dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, releasenotes/notes/QM.add_linear-default_vartype-370a4876806affb0.yaml, tests/test_quadratic_model.py
Useful in some of the same circumstances as https://github.com/dwavesystems/dimod/pull/1158
=> Add default_vartype to QM.add_linear() and QM.add_linear_from()

requirements.txt
See https://github.com/dwavesystems/dimod/issues/1169#issuecomment-1105462848.
=> Update cython version in requirements.txt to 0.29.28

dimod/constrained.py, releasenotes/notes/set-penatly-to-one-zero-objective-116b50b47ad41051.yaml, tests/test_constrained.py
If the objective is empty, set the Lagrange to one.
=> Bug fix nonzero lagrange multiplier

releasenotes/notes/feature-c++-lp-reader-1d5109d86ce778ed.yaml
Thanks to @randomir for the good catch.
=> Fix release note for LP

releasenotes/notes/drop-pyparsing-c832c79ef5031e07.yaml, requirements.txt, setup.py
=> Drop pyparsing requirement

README.rst
...and remove the hardcoded python version reference.
=> Simplify install instructions

dimod/constrained.py, dimod/lp.py, docs/reference/constrained.rst, releasenotes/notes/add-CQM.to_lp_file-method-2a4a5fa0fc9156eb.yaml, tests/test_constrained.py
This PR is based on and supplants #1052.
=> Add ConstrainedQuadraticModel.to_lp_file() method

dimod/constrained.py, dimod/decorators.py, dimod/utilities.py, releasenotes/notes/random-labels-lp-1b2b09a957f2650c.yaml, tests/test_lp.py
=> Make randomly generated labels LP file safe

dimod/include/dimod/quadratic_model.h, releasenotes/notes/cpp-qm-abstract-base-class-6d13f02b0464fe2a.yaml
Unfortunately this introduces a binary incompatibility. Will have to wait until 0.12.0
=> Refactor QuadraticModelBase::add_quadratic and QuadraticModelBase::set_quadratic

.circleci/config.yml, dimod/include/dimod/iterators.h, dimod/include/dimod/quadratic_model.h, testscpp/Makefile, testscpp/test_main.cpp, testscpp/tests/test_quadratic_model.cpp, testscpp/tests/test_utils.cpp
See https://github.com/dwavesystems/dimod/issues/1238, https://github.com/dwavesystems/dimod/issues/1239, https://github.com/dwavesystems/dimod/issues/1240
Ideally we would test with the clang/gcc versions used by manylinux. But this is a lot simpler and gives us decent coverage.
=> Update C++ testing framework

dimod/include/dimod/abc.h, dimod/include/dimod/constraint.h, dimod/include/dimod/expression.h
I know these are missing tests, but they are tested in #1264 and in some forthcoming changes in #1263 . I am pulling these changes out now to keep the review relatively clean.
=> Fix/Add a few utility C++ methods

dimod/binary/binary_quadratic_model.py, dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/cyqmbase/cyqmbase_template.pyx.pxi, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py
=> Rework QM/BQM serialization to share more code

dimod/include/dimod/expression.h, releasenotes/notes/fix-remove-variables-344b24d9044b0030.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
Replaces https://github.com/dwavesystems/dimod/pull/1273
=> Fix C++ CQM.remove_variables()

dimod/libcpp/abc.pxd, dimod/libcpp/binary_quadratic_model.pxd, dimod/libcpp/lp.pxd, dimod/libcpp/quadratic_model.pxd, dimod/libcpp/vartypes.pxd, setup.py
This lets Cython detect changes to the include files and recompile appropriately.
=> Specify include path in .pxd files rather than setup.py

dimod/include/dimod/constrained_quadratic_model.h, testscpp/tests/test_constrained_quadratic_model.cpp
Also adds a few more tests I wrote while debugging.
=> Fix C++ CQM copy assignment to correctly deepcopy constraints

dimod/binary/binary_quadratic_model.py, dimod/constrained/cyexpression.pyx, dimod/views/quadratic.py, releasenotes/notes/feature-restore-some-objective-and-constraint-methods-cc40b8ac28944ee2.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/1287
=> Restore some removed methods for CQM manipulation

dimod/constrained/cyconstrained.pyx, dimod/include/dimod/abc.h, dimod/libcpp/constrained_quadratic_model.pxd, releasenotes/notes/constraint-move-befce0fefaec3d95.yaml, tests/test_constrained.py
Contains the commit from #1294
=> Fix the ``move`` kwarg in ``CQM.add_constraint_from_model()``

dimod/constrained/constrained.py, releasenotes/notes/single-variable-discrete-constraints-1b5730928fe19041.yaml, tests/test_constrained.py
Closes https://github.com/dwavesystems/dimod/issues/1281
=> Allow discrete constraints to have 0 or 1 variable

dimod/include/dimod/lp.h, dimod/libcpp/lp.pxd, dimod/lp.py, releasenotes/notes/fix-lp-maximization-cd4eaf8fe126321e.yaml, releasenotes/notes/lp-error-type-5c2d19ac037c0ccf.yaml, tests/test_lp.py
Closes https://github.com/dwavesystems/dimod/issues/1321
=> Fix LP-file loading to correctly handle maximization

dimod/include/dimod/constraint.h, dimod/include/dimod/expression.h, releasenotes/notes/c++-constraint.clear-1f655c7a701efd58.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
Closes https://github.com/dwavesystems/dimod/issues/1330
=> Add C++ Constraint::clear() method

dimod/generators/fcl.py, releasenotes/notes/fix-frustrated-loop-tuple-labels-0ec17b68ee6cfd42.yaml, tests/test_generators.py
This function really needs an overhaul for performance, but I tried to keep the changes minimal for now.
Closes https://github.com/dwavesystems/dimod/issues/1342
=> Fix frustrated_loop()'s handling of graphs with tuple labels

dimod/generators/__init__.py, dimod/generators/magic_square.py, releasenotes/notes/cqm-magic-square-generator-36a9de45609ce0be.yaml, tests/test_generators.py
Adding a (normal) magic square generator to the generators package. 
[Magic squares](https://en.wikipedia.org/wiki/Magic_square) are quadratic constrained integer problems of size $n^2$ with no objective.
=> Magic square generator

dimod/include/dimod/constrained_quadratic_model.h, releasenotes/notes/remove-constraints-if-dfa2734c9566e1b2.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
This method provides a significant speedup when removing constraints in bulk at the C++ level.
=> Add C++ CQM::remove_constraints_if() method

dimod/__init__.py, releasenotes/notes/smaller-wheels-ee4d7c548b83ff29.yaml
I have manually tested the wheels with `dwave-preprocessing` and `dwave-samplers` in case of any binary compatibility issues.
=> Update version number

dimod/generators/random.py, releasenotes/notes/add-power-r-d2b36435623c72cc.yaml, tests/test_generators.py
Weights follow a power-law distribution with respect to their magnitude. Good for high precision instances.
=> add power-r generator

dimod/generators/binpacking.py, docs/reference/generators.rst, releasenotes/notes/binpacking-generator-746ead56b214c5ce.yaml
Added a bin packing generator that allows for a list of weights and capacity to be passed in instead of randomly generating these values.
Updated the old random_bin_packing generator to call the new generator and pass in the random values.
Notes:
- I did not add more tests as the random_bin_packing generator is using bin_packing but I can add specific tests for bin_packing if that is preferred.
- Also please advice on release notes I am new to these.
=> Bin Packing Generator

dimod/generators/knapsack.py, docs/reference/generators.rst, releasenotes/notes/knapsack-generator-59e48aaaf07cb8ac.yaml, tests/test_generators.py
A knapsack generator that allows for custom values, weights, and capacity to be passed in instead of randomly generating these values.
Updated the old random_knapsack generator to call the new generator and pass in the random values.
Added additional test to check if the shapes of values and weights are equal.
=> Knapsack Generator

dimod/generators/multi_knapsack.py, docs/reference/generators.rst, releasenotes/notes/multi-knapsack-generator-cf29619dec749a1a.yaml, tests/test_generators.py
A multiple knapsack generator that allows for custom values, weights, and capacities to be passed in instead of randomly generating these values.
Updated the old `random_multi_knapsack` generator to call the new generator and pass in the random values.
Added additional test to check if the shapes of values and weights are equal.
=> Multiple Knapsack Generator

dimod/core/__init__.py, dimod/core/composite.py, dimod/core/initialized.py, dimod/core/polysampler.py, dimod/core/sampler.py, dimod/core/scoped.py, dimod/core/structured.py, dimod/discrete/discrete_quadratic_model.py, dimod/quadratic/quadratic_model.py, dimod/reference/composites/higherordercomposites.py, dimod/reference/composites/truncatecomposite.py, docs/reference/sampler_composites/api.rst, releasenotes/notes/add-scoped-abc-53b64b69ddd5c1ac.yaml, tests/test_composite.py, tests/test_sampler.py, tests/test_scoped.py
Addresses https://github.com/dwavesystems/dwave-system/issues/555 on a lower-level.
=> Add scoped resource support

dimod/core/composite.py, dimod/core/polysampler.py, releasenotes/notes/fix-composedsampler-inheritance-92966dac7eb1128c.yaml, tests/test_composite.py
=> Fix composed sampler inheritance order
