dwavesystems/dimod

README.md
To check the build status easily, the Travis CI status badge is added to README.
=> Added Travis CI status badge to README

dimod/response.py, tests/test_response.py
When iterating over the rows in the samples DataFrame, the series
were not being correctly indexed.
=> Fix bug in Response.data

dimod/binary_quadratic_model.py
Use the standard `other` instead of `bqm`.
=> Minor refactor: renamed arguments in BQM.{__eq__,__ne__}

dimod/compatibility23.py, dimod/core/sampler.py, dimod/decorators.py, tests/test_decorators.py
Support default argument values. Use `TypeError` consistently with Python's standard usage.
=> Refactor @vartype_argument

dimod/response.py, setup.py
Build a Response object from a list of futures. Futures supported are
`concurrent.futures.Future` or `dwave.cloud.qpu.computation.Future`.
=> Implement Response.from_futures()

.travis.yml
Explicitly use python3 when creating virtualenv; looks like the global
python is now py2.
=> Fix Travis Py3/OSX build

dimod/binary_quadratic_model.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py
=> Update BQM to allow for metadata in an `info` field and to be built from empty

MANIFEST.in, dimod/binary_quadratic_model.py, dimod/io/bqm_json_schema.json, dimod/io/json.py, docs/reference/binary_quadratic_model.rst, requirements.txt, setup.py, tests/test_binary_quadratic_model.py
#152 
Example of the json schema:
```
{
"linear_terms": [
{"bias": 1.0, "label": 0},
{"bias": -1.0, "label": 1}
],
"info": {},
"offset": 0.5,
"quadratic_terms": [
{"bias": 0.5, "label_head": 1, "label_tail": 0}
],
"variable_labels": [0, 1],
"variable_type": "SPIN",
"version": {
"bqm_schema": "1.0.0",
"dimod": "0.6.3"
}
}
```
=> Add json encoding/decoding to BinaryQuadraticModel

dimod/binary_quadratic_model.py, dimod/reference/samplers/random_sampler.py, dimod/response.py, tests/test_binary_quadratic_model.py, tests/test_random_sampler.py
By overwriting `SampleView.items` and `SampleView.values` we get approximately 10x speed up for calculating energies of a response.
Addresses #135 as well
=> Speed up calculating the energy from responses

tests/test_binary_quadratic_model.py
Dance around deficiencies in `pandas.DataFrame.dot()` implementation to
avoid sorting the index array with mixed types (and throwing `TypeError`
wrapped with `RuntimeWarning`).
Post-mortem:
- [`pandas.DataFrame.dot`](https://github.com/pandas-dev/pandas/blob/a00154dcfe5057cb3fd86653172e74b6893e337d/pandas/core/frame.py#L821) calculates a union of indices (variables) of
left- and right-hand-side DataFrame/Series to align them before multiplying
- [`pandas.Index.union`](https://github.com/pandas-dev/pandas/blob/a00154dcfe5057cb3fd86653172e74b6893e337d/pandas/core/indexes/base.py#L2189) returns early (does nothing) if two indices it has to
combine are equal. If indices differ (even just in order), the method joins them,
and just for a good measure, [sorts …
=> Bug fix: RuntimeWarning thrown in BQM unittests

dimod/response.py, tests/test_response.py
* Response.samples(n) now limits the number of samples returned
* All Response.data_vectors are now stored as numpy arrays
Closes #172 
Closes #173
=> QOL changes for Response

dimod/embedding/transforms.py, tests/test_embedding.py
```
embedding = {0: [0, 1], 1: [2], 2: [3]}
G = nx.cycle_graph(4)
bqm = dimod.BinaryQuadraticModel.from_qubo({(0, 0): 1})
target_bqm = dimod.embed_bqm(bqm, embedding, G)
for v in itertools.chain(*embedding.values()):
assert v in target_bqm
```
Previously failed but now works
=> Add all chain variable to target bqm with embed_bqm

dimod/embedding/transforms.py, tests/test_embedding.py
This is not handled in unembed_response(), so will fail anyway
Better to fail during embedding for a clearer error message
Handled in dwave.system.composites.EmbeddingComposite()
=> Remove option to embed singleton variables

README.rst, dimod/core/sampler.py, docs/index.rst
@arcondello RtD first page currently has a prominent "Learn more about dimod on Read the Docs" and the "The example’s QUBO form, E(ai,bi,j;qi)=−q1−q2+2q1q2..." isn't connected to its example.
As discussed, I am removing examples from abstract sampler class so they're not inherited
=> Remove abstract sampler examples, rearrange items on RtD 1st page & 

dimod/binary_quadratic_model.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py
Add two new method `BinaryQuadraticModel.to_numpy_vectors` and `BinaryQuadraticModel.from_numpy_vectors`. This serves as a sparse alternative to `to_numpy_matrix` and `from_numpy_matrix`.
=> Add `to_numpy_vectors`, `from_numpy_vectors` to BQM

dimod/binary_quadratic_model.py, tests/test_binary_quadratic_model.py
BQM already acts as an iterable container, but `variables` property is more explicit and it supports efficient set operations.
=> Add BQM.variables property

dimod/binary_quadratic_model.py, dimod/io/bqm_json_schema.json, dimod/io/json.py, docs/reference/binary_quadratic_model.rst, tests/test_binary_quadratic_model.py, tests/test_io_json.py
**This is a backwards compatibility break**
Simplifies the `BinaryQuadraticModel.to_json` method to always return a string. We also remove a lot of boilerplate used to encode bqms with low memory footprint. That case will be covered by #235 .
We will also close #218 as redundant. In order to prevent having too many serialization methods, we don't include `to_dict`/`from_dict`.
=> to_json/from_json

dimod/core/sampler.py, dimod/core/structured.py, docs/introduction.rst
In some examples of docstring, deprecated method `Response.from_dicts` is used.
This pull request replaces `Response.from_dicts` by `Response.from_samples`.
=> Replace Response.from_dicts by Response.from_samples in docstring

dimod/core/sampler.py, tests/test_sampler.py
**Issue**
* The illegal argument: `data_vector_offsets` of `change_vartype` is used in `Sampler.sample`
* There is no test to call `Sampler.sample` from `Sampler.sample_qubo` or `Sampler.sample_ising`
**Fix**
* Replaced  `data_vector_offsets` with `energy_offset` which is correct argument of `change_vartype`
* Added tests to call `Sampler.sample`
=> Fix illegal argument of change_vartype in Sampler.sample

dimod/binary_quadratic_model.py, dimod/io/bson.py, docs/conf.py, docs/reference/binary_quadratic_model.rst
Hopefully this is the last attempt. Add two methods:
```
BinaryQuadraticModel.to_serializable()
BinaryQuadraticModel.from_serializable()
```
We also deprecate `to_json`, `from_json`, `to_bson`, `from_bson`.
=> Add to_/from_serializable

dimod/embedding/transforms.py, tests/test_embedding_transforms.py
Closes #246 
We do not throw a warning here, that is left to the calling method/composite to do.
=> Add chain_break_fraction kwarg to unembed_response

dimod/io/coo.py
@arcondello I don't think "vartype is not vt[0]" works because the two are never the same object. I think you meant "vartype != vt[0]". That works for 
```with open('test.qubo', 'r') as file:
...:     bqm = dimod.BinaryQuadraticModel.from_coo(file, 'BINARY') ```
but not for 
```with open('test.qubo', 'r') as file:
...:     bqm = dimod.BinaryQuadraticModel.from_coo(file, dimod.BINARY)```
A long-term fix is to see if they are the same vartype in case someone uses "# vartype=dimod.BINARY" in the file itself. But this at least lets me read files like the HADES problem files that have headers:
```# vartype: BINARY
0 4 -1.000000
0 5 -1.000000
0 6 0.000000```
Now these give me " vartypes from headers and/or inputs do not match" erros
=> Fix vartype test

.circleci/config.yml, dimod/__init__.py, dimod/roof_duality/fix_variables.py, docs/reference/bqm_functions.rst, setup.py
If for some reason the `python setup.py build_ext` command fails (either no available compiler or boost is not installed), the roof_duality extension is ignored.
Related to #281
=> Allow c++ extension build to fail gracefully.

.appveyor.yml
This should attempt to deploy and fail for lack of credentials. But it still should discover twine without it being present in scripts.
=> WIP: Don't force reinstall twine in appveyor

dimod/binary_quadratic_model.py, dimod/reference/composites/scalecomposite.py, tests/test_binary_quadratic_model.py, tests/test_scalecomposite.py
* Normalize in BQM function now ignores the ignored_variable/ignored_interactions when calculating the scalar. 
* doc fixes in scaleComposite and its tests
* turned optional arguments in helper functions of scalecomposite into mandatory arguments. 
Closes #375
=> minor scaling updates

dimod/binary_quadratic_model.py, dimod/views.py, tests/test_binary_quadratic_model.py
In the case that the linear biases are not specified by the user and are assumed to be 0, we don't store them in the underlying `BQM._adj` dict-of-dicts.
=> Do not keep unset linear biases in memory

dimod/sampleset.py, tests/test_sampleset.py
Restore the `SampleSet.data_vectors` property.
Closes #393
=> SampleSet.data_vectors

dimod/serialization/format.py, tests/test_serialization_format.py
Have no idea why I used `type(obj) is` rather than `isinstance`...
=> Fix bug from printing Response objects

dimod/sampleset.py
`SampleSet.relabel_variables` acted on `SampleSet._variables` which meant that if the `SampleSet` was constructed from a future and the future has not been resolved yet that it would fail.
=> SampleSet.relabel_variables now correctly resolves the future

dimod/reference/composites/fixedvariable.py, docs/reference/ref_samplers_composites.rst, tests/test_fixedvariablecomposite.py
Add a composite that uses roof duality to fix the variables before invoking the child sampler
=> Add RoofDualityComposite

dimod/views/samples.py, tests/test_sampleset.py
The change introduced in #439 was backwards compatibility breaking. This restores backwards compatibility. However, using `SampleSet.samples` as an iterator is deprecated and will be removed in the future.
See https://github.com/dwavesystems/dwave-hybrid/issues/124
Closes #449 as redundant
=> Make SampleSet.samples an iterator

dimod/sampleset.py, tests/test_sampleset.py
Closes #461 
I took a look at the source for `numpy.unique` to see if there is a more direct way to do it, but I think it still make sense to leverage numpy's implementation rather than write our own.
=> SampleSet.aggregate() preserves order

dimod/binary_quadratic_model.py
I think the risk a user inadvertently creates mismatched-length vectors and gets a BQM that is silently truncated by 
```
quadratic = {(variable_order[u], variable_order[v]): float(bias)
for u, v, bias in zip(heads, tails, values)}
``` 
, which will be hard to diagnose, especially for large numbers of variables, is high and the inconvenience of maybe having to set shorten vectors that would have been happily trimmed is not a big deal.
=> Prevent from_numpy_vectors from silently truncating 

dimod/binary_quadratic_model.py, dimod/decorators.py, dimod/exceptions.py, dimod/utilities.py, dimod/views/bqm.py, tests/test_binary_quadratic_model.py
Note that at the moment the `vartype` property is writeable (see #489 ).
=> BinaryQuadraticModel.is_writeable

dimod/sampleset.py, dimod/variables.py, tests/test_sampleset.py
Right now if the underlying Numpy array is edited while the sample set is not writeable, a `ValueError` will be raised, rather than a `WriteableError`.
=> Add SampleSet.is_writeable

dimod/binary_quadratic_model.py, tests/test_binary_quadratic_model.py
Fixed a small bug in contract_variables(): when v is contracted into u, the linear bias for v should be added to that of u. Alex, let me know what I did wrong with the pull request process...
=> fixed bug in contract_variables()

dimod/serialization/json.py, requirements.txt, setup.py
`jsonschema` was only used for a legacy serialisation method, since that functionality is deprecated it makes sense to remove the dependency.
=> Remove jsonschema dependency

dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/adjdictbqm.py, dimod/bqm/adjmapbqm.pxd, dimod/bqm/adjmapbqm.pyx, dimod/bqm/adjvectorbqm.pxd, dimod/bqm/adjvectorbqm.pyx, dimod/vartypes.py, tests/test_bqm.py
Construction now looks like
```
bqm = BQM(dimod.BINARY)  # empty
bqm = BQM(np.ones((5, 5)), dimod.BINARY)
bqm = BQM((h, J), dimod.SPIN)
bqm = BQM((h, J, offset), dimod.SPIN)
bqm = BQM(5, dimod.BINARY)  # 5 variables, 0 interactions
```
=> Add offset and vartype properties to cybqm

dimod/bqm/__init__.py, dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h, dimod/bqm/src/adjmap.cc, dimod/bqm/src/adjmap.h, dimod/bqm/src/adjvector.cc, dimod/bqm/src/adjvector.h, setup.py, tests/test_adjarraybqm.py, tests/test_adjmapbqm.py, tests/test_adjvectorbqm.py
Only the dictionary backend will be available in python2.7 and 3.4.
This allows us to use some of the newer c++ features like type aliases because we don't need to support visual studio 9.0
=> Only make cybqms available in python 3.5+

dimod/higherorder/utils.py, tests/test_higherorder.py
Support vartype inputs in different formats, partially addresses #550 . Previously `make_quadratic` required ` Vartype` enum, rather than also supporting the string and set inputs.
=> Support vartype str/set inputs in make_quadratic

dimod/bqm/adjarraybqm.pxd, dimod/bqm/adjarraybqm.pyx, dimod/bqm/cppbqm.pxd, dimod/bqm/shapeablebqm.pyx.src, dimod/bqm/src/adjarray.cc, dimod/bqm/src/adjarray.h
This makes function overloading a lot nicer e.g.
```
num_variables(bqm) // for all
```
rather than
```
num_variables(invars, outvars)  // for array
num_variables(bqm)  // for map, vector
```
=> Store an adjarray bqm in c++ as a pair (invars, outvars)

dimod/reference/composites/connectedcomponent.py
When fixing the independent variables, the value of the fixed variable has no effect. However, if a solver checks for valid values only, we need to pass 0 or 1 for 'BINARY' and -1 or 1 for 'SPIN'. This pull request fixes this issue.
=> Fix variables to one of the allowed values

LICENSE, dimod/core/composite.py, docs/conf.py, docs/reference/bqm/binary_quadratic_model.rst, docs/reference/sampler_composites/composites.rst, docs/reference/sampler_composites/higher_order_composites.rst
Currently SDK unified docs builds with >300 warnings. These changes get rid of all warnings generated by a dimod build.
=> Build sdk without dimod warnings

dimod/sampleset.py
when trying to deserialize from version 2.0.0 of serialization, I encountered a problem in which the shape is saved as float hence causing issues in unpacking. I do not know how it managed to save it as float since I did not interfere with the process but changing it so that we are always passing an int for index and shape
=> fix float index issue

MANIFEST.in, dimod/include/dimod/README.rst, dimod/utilities.py, setup.py
Follows NumPy's pattern.
#630 should be rebased to use it.
Also roof duality's code, see #519.
=> Add a unified include path for dimod headers

dimod/utilities.py, tests/test_utilities.py
=> Allow ising_to_qubo to be provided with an underspecified linear

dimod/include/dimod/adjarraybqm.h, dimod/include/dimod/adjmapbqm.h, dimod/include/dimod/adjvectorbqm.h
Gives slightly nicer access to the linear biases in c++ BQMs. E.g.
```
bqm.linear(v) += 1;
```
rather than
```
bqm.set_linear(v, bqm_get_linear(v) + 1);
```
I would love to have `bqm.quadratic(u, v)` as well, but because we keep two copies of the bias around for quadratic, we can't just return a reference like we do with `.linear`. Open to suggestions.
=> Add Adj*BQM::linear

dimod/decorators.py, dimod/reference/composites/scalecomposite.py, docs/reference/utilities.rst, tests/test_decorators.py
This decorator is intended to make it easier to construct non-blocking composites, (e.g. would have simplified #555,  #677).
This approach might be convenient for expert users, but I am worried that it obfuscates the implementation in a confusing way.
=> Decorator for nonblocking sample methods

dimod/bqm/cppbqm.pxd, dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, docs/reference/dqm.rst, tests/test_discrete_quadratic_model.py
Also adds intermediate representation in `DQM.to_numpy_vectors` and `.from_numpy_vectors`.
Also uses the API suggested in #599.
=> DQM Serialization

dimod/discrete/discrete_quadratic_model.py, tests/test_discrete_quadratic_model.py
Closes #729 
Closes #730 
This is technically a backwards compatibility break, but since it only affects a fairly internal object, I think it is OK.
=> Fix some issues in the object returned by DQM.to_file

setup.py
Closes #732
Occurs because the roof duality code is not supported in c++17
=> Use c++11 with MSVC

.circleci/config.yml, requirements.txt, setup.py, tests/requirements.txt
Makes extensive use of circle-ci's matrix functionality. Also adds tests for numpy ranges.
Closes #733 as redundant.
=> Refresh circleci and support python 3.9

.clang-format, dimod/include/dimod/adjarraybqm.h, dimod/include/dimod/adjmapbqm.h, dimod/include/dimod/adjvectorbqm.h, dimod/include/dimod/utils.h, testscpp/tests/test_bqm.cpp, testscpp/tests/test_roofduality.cpp
See https://github.com/dwavesystems/dwave-ocean-sdk/pull/90 and https://github.com/dwavesystems/dwave-ocean-sdk/pull/103
=> Add .clang-format and apply to dimod/include/*

dimod/bqm/shapeablebqm.pyx.src, dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/include/dimod/adjvectorbqm.h, dimod/utilities.py, tests/test_discrete_quadratic_model.py, tests/test_utilities.py
And create some functions to abstract away some of the type coercion.
Closes #762 
See also #761, this PR disallows self loops when constructing from NumPy arrays
=> Refactor DQM.from_numpy_vectors

docs/reference/sampler_composites/composites.rst, docs/reference/sampler_composites/index.rst, docs/reference/sampler_composites/samplers.rst
Dimod part of fix for https://github.com/dwavesystems/dwave-system/issues/380 together with https://github.com/dwavesystems/dwave-system/pull/381.
Also makes content lists of samplers/composites look nicer
=> Add references to additional sampler/composites 

dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, tests/test_discrete_quadratic_model.py
Add a method to `dimod.discrete_quadratic_model` to convert linear constraints to a quadratic objective.
=> add add_constraint_as_quadratic method to DQM and cyDQM

dimod/variables.py, tests/test_variables.py
This kwarg argument is useful for other refactoring work I am doing but wanted to break it out so it's easier to review.
=> Deprecate Variables.index mapping and add permissive kwarg

dimod/reference/composites/spin_transform.py
Composed samplers don't need to be structured anymore:  https://github.com/dwavesystems/dwave-system/pull/191
=> remove the (non-implemented) handling of a Structured child sampler

MANIFEST.in
setuptools in windows couldn't handle the trailing `/`.
I tested with a different CI script. I don't think it makes sense to add it permanently to the CI as a test
=> Fix missing .pxd files in windows wheels

.gitignore, dimod/cyvariables.pxd, dimod/cyvariables.pyx, dimod/discrete/discrete_quadratic_model.py, dimod/sampleset.py, dimod/variables.py, docs/reference/dqm.rst, docs/reference/index.rst, docs/reference/variables.rst, setup.py, tests/test_variables.py
Results in 10-20x speedup on many common operations in SampleSet and DQM classes. Also opens up the path for accessing it from cython for even more improvement for performance-critical applications.
=> Cythonize the variables object

.circleci/config.yml, MANIFEST.in, dimod/__init__.py, dimod/package_info.py, pyproject.toml, requirements.txt, setup.cfg, setup.py
Significantly rework/simplify the setup script.
Closes #678
=> Setup refresh

dimod/include/dimod/quadratic_model.h, docs/reference/cpp.rst, testscpp/tests/test_quadratic_model.cpp
First of several PRs breaking up one big one. This will replace the other dimod BQM C++ implementation. Also can be easily sub-classed for other types of quadratic models.
=> Implement QuadraticModelBase and BinaryQuadraticModel in C++

dimod/decorators.py, docs/reference/utilities.rst, docs/requirements.txt, tests/requirements.txt, tests/test_decorators.py
This gives the same result as
```
from functools import cached_property
class Inner:
def func(self):
return 1
class Outer:
def __init__(self):
self.inner = Inner()
@cached_property
def func(self):
return self.inner.func
```
but also works with type annotations and docstrings.
=> Add forwarding_method decorator

MANIFEST.in
=> Fix missing .pxd files in win wheels

dimod/core/structured.py, tests/test_structured.py
Feels a little clunky, reviews appreciated :)
Closes #830
=> check bqm feature first pass

setup.cfg
Now that we're starting to use python's typing module, 80 chars is becoming increasingly restrictive.
This commit signals that dimod support 100 characters by adding it to the `setup.cfg`. Ideally we would like to add it to the `pyproject.toml`, but right now that's not supported. See https://github.com/PyCQA/pycodestyle/issues/813
=> Allow 100 character line length

dimod/__init__.py, dimod/binary/binary_quadratic_model.py, dimod/sym.py, tests/test_bqm.py
Add very simple operator overloading to the BQM object.
Right now `__add__` etc create a new BQM object, rather than something like
```
Add = namedtuple('Add', ['lhs', 'rhs'])
class BQM:
...
def __add__(self, other):
return Add(self, other)
```
Returning a relation object like above has performance advantages (at the cost of memory), but it's a lot less flexible and a lot less self-contained. For instance, right now
```
ss = ExactSolver().sample(bqm0 + bqm1)
```
is defined without needing some sort of resolution step.
One way around this would be to make comparisons full-fledged BQM data classes (e.g. [pyBQM](https://github.com/dwavesystems/dimod/blob/be747fa4be2c898f7460f77573f82d35f634df57/dimod/binary/pybqm.py#L35) or [VartypeView](https://github.com/dwavesystems/dimod/blob/be747fa4be2c …
=> Add symbolic manipulation of BQM objects

dimod/__init__.py, dimod/constrained.py, dimod/cyvariables.pyx, dimod/variables.py, tests/test_constrained.py
Allows the construction of binary constrained quadratic models.
=> Add minimal CQM implementation

dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, tests/test_discrete_quadratic_model.py
Note: Publishing before it's ready to merge to get eyes on it.
Implement offset in DQM object via underlying `cyDiscreteQuadraticModel` object.
Update methods in backwards compatibility safe way.
Add new tests and update existing tests to reflect offset.
Closes https://github.com/dwavesystems/dimod/issues/744
=> Add offset to dqm

dimod/include/dimod/quadratic_model.h, releasenotes/notes/quadratic_model_scale_method-52f5a73ec045801c.yaml, testscpp/tests/test_quadratic_model.cpp
Implement `scale` method in `QuadraticModelBase`.
Adjust offset, linear biases, and interactions by a scale factor.
Add test to reflect addition.
Closes #833
=> Add `scale` method to `QuadraticModelBase`, with test

dimod/binary/binary_quadratic_model.py, dimod/binary/cybqm/cybqm_template.pxd.pxi, dimod/binary/cybqm/cybqm_template.pyx.pxi
Port `QuadraticModelBase::scale` to Python layer of BQM.
Benchmark done using `dimod.generators.random.gnm_random_bqm`, fixed with 100,000 variables and 1,000,000 interactions. Comparison done with `cls = AdjVectorBQM` and `cls = dimod.binary.BinaryQuadraticModel` respectively:
`1.4 s ± 7.43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)` (`AdjVectorBQM` scale method pure python)
`102 ms ± 651 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)` (`BinaryQuadraticModel` defaulting to C++ code)
=> Make use of QuadraticModelBase::scale in dimod.binary.BQM

.circleci/config.yml
Apply  delvewheel.
https://github.com/dwavesystems/dimod/issues/870#issue-935320117
=> Use delvewheel.

dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, releasenotes/notes/dqm-use-stable-c++-bqm-51c61c29d2d74263.yaml
Use the new C++ BQM introduced in https://github.com/dwavesystems/dimod/pull/818 in `DiscreteQuadraticModel`.
*Additional Context*
`DQM.add_linear_equality_constraint` performance has changed. Using the following script
```
import time
import numpy as np
import dimod
num_variables = 1000
num_cases = 10
num_trials  = 5
ordered = True
rng = np.random.default_rng(42)
terms_list = [[(v, rng.choice(num_cases), 1) for v in range(num_variables)] for _ in range(10)]
if not ordered:
for terms in terms_list:
rng.shuffle(terms)
single = 0
additive = 0
for _ in range(num_trials):
dqm = dimod.DQM()
for v in range(num_variables):
dqm.add_variable(num_cases)
t = time.time()
dqm.add_linear_equality_constraint(terms_list[0], 1, 1)
single += time.time() - t
t = time.time()
for terms in terms_list: …
```
=> Use new C++ BQM in DiscreteQuadraticModel

docs/requirements.txt
With `sphinx 4.1.1` or `4.1.0`, the following error occurs when running the doc test:
```
Exception occurred:
File "/home/circleci/repo/env/lib/python3.7/site-packages/sphinx/util/cfamily.py", line 275, in fail
raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 5]
class
-----^
```
It appears to be the same problem as this: https://github.com/sphinx-doc/sphinx/issues/9433 , and should be fixed in `breathe`: https://github.com/michaeljones/breathe/pull/711 . Once a patch is released, we can probably remove this upper bound.
=> Set temp upper bound on sphinx to remove doc test error

dimod/__init__.pxd, dimod/binary/__init__.pxd, dimod/binary/binary_quadratic_model.py, dimod/binary/cybqm/cybqm_template.pxd.pxi, dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/binary/pybqm.py, dimod/binary/vartypeview.py, dimod/constrained.py, dimod/quadratic/__init__.pxd, dimod/quadratic/cyqm/__init__.pxd, dimod/quadratic/cyqm/cyqm_template.pxd.pxi, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, releasenotes/notes/BQM.data.vartype-method-ba96dce5716ffa4c.yaml, releasenotes/notes/CQM.add_discrete-return-label-758b7756d0fc378b.yaml, releasenotes/notes/cimport-cyBQM-and-cyQM-77968e09ebcd685d.yaml, releasenotes/notes/cyBQM-and-cyQM.data-20ce921b78af8cdd.yaml, tests/test_constrained.py
A grab bag of small updates to make CQM, BQM and QM behave more consistently.
Technically the change to `.vartype()` from `.vartype` in the underlying data object is a backwards compatibility break, but it was not used in https://github.com/dwavesystems/dwave-preprocessing/pull/22 so I think it's safe to deploy in 0.10.1.
=> Consistency Update

dimod/binary/binary_quadratic_model.py, dimod/quadratic/quadratic_model.py, releasenotes/notes/Binaries-and-Spins-and-Integers-bfed01e0c2b5f6cd.yaml, tests/test_bqm.py, tests/test_quadratic_model.py
Decided to go with iterators rather than lists, as a user can always make a list from a iterator, but if for whatever reason they want to do something like
```
for x in Binaries(1000):
...
```
we don't need to make all 1000 of them at once.
I also stuck with capitalization, to be consistent with `Binary`, `Spin`, and `Integer`, although it's starting to get a bit weird... In a followup PR I might use lower case and deprecate the capitalized ones.
Closes https://github.com/dwavesystems/dimod/issues/918
=> Add Spins, Binaries and Integers functions

dimod/binary/binary_quadratic_model.py, dimod/quadratic/quadratic_model.py, docs/reference/quadratic.rst, releasenotes/notes/add-quicksum-373672fff48775a4.yaml, tests/test_symbolic.py
There is probably still more performance on the table, but this already provides a pretty nice speedup and we can encourage people to use it and improve it more later.
Testing locally,
```python
import time
import dimod
t = time.time()
sum(dimod.Binary(v) for v in range(10000))
print(time.time() - t)
t = time.time()
dimod.quicksum(dimod.Binary(v) for v in range(10000))
print(time.time() - t)
```
returns
```bash
1.0739736557006836
0.1277778148651123 
```
=> Add quicksum function

dimod/constrained.py
The CQM is defined over binary and integer variables, discrete variables are not natively handled. The docstring was wrongly reporting discrete variables. Removed.
=> corrected variable types in cqm docstring

dimod/binary/binary_quadratic_model.py, dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, releasenotes/notes/permissive-energies-ce39fea1c68d074b.yaml, tests/test_bqm.py, tests/test_quadratic_model.py
Closes https://github.com/dwavesystems/dimod/issues/949
I decided not to go with the `strict` keyword argument. It occurs to me that we may want `strict` to refer to either the set of variables, the vartype, or both. For now, I am going to leave it alone and we can add that feature when it's requested (see https://github.com/dwavesystems/dimod/issues/954)
=> Support a superset of variables in BQM/QM.energies

dimod/core/initialized.py, dimod/sampleset.py, releasenotes/notes/fix-as_samples-and-parse_initialized_states-ed9097448745a6f6.yaml, tests/test_initialized.py, tests/test_sampleset.py
Fixes #861 and https://github.com/dwavesystems/dwave-tabu/issues/86
- Ensure that ``copy`` argument is not ignored in ``as_samples``
- Work on a copy of the input data in ``parse_initial_states`` when needed, so that input is not modified
=> Fix ``as_samples`` and ``parse_initial_states``

dimod/constrained.py, docs/reference/constrained.rst, releasenotes/notes/cqm-to-bqm-d369043cc341c5a3.yaml, tests/test_constrained.py
*Example usage*
Start with a constrained quadratic model
```python
>>> num_widget_a = dimod.Integer('num_widget_a', upper_bound=7)
>>> num_widget_b = dimod.Integer('num_widget_b', upper_bound=3)
>>> cqm = dimod.ConstrainedQuadraticModel()
>>> cqm.set_objective(-3 * num_widget_a - 4 * num_widget_b)
>>> cqm.add_constraint(num_widget_a + num_widget_b <= 5, label='total widgets')
'total widgets'
```
Convert it to a binary quadratic model and solve it using `dimod.ExactSolver`.
```python
>>> bqm, invert = dimod.cqm_to_bqm(cqm)
>>> sampleset = dimod.ExactSolver().sample(bqm)
```
Interpret the answer in the original variable classes
```python
>>> invert(sampleset.first.sample)
{'num_widget_a': 2, 'num_widget_b': 3}
```
=> Add `cqm_to_bqm` function

.circleci/config.yml, requirements.txt, setup.py
This is to enable dwave-system (>1.7.0) to support both dimod 0.9 and
0.10.
Although now we have duplicated composites (available in both dimod
and dwave.preprocessing namespaces), this is necessary to resolve
unsatisfiable dependencies when dwave-system 1.7.x is installed with
dimod 0.9.x (due to dwave-preprocessing introduced as extras dependency
in dimod 0.10.0 and then removed in 0.10.5). This makes specifying dimod
as a dependency in dwave-system impossible, if we want to allow both 0.9
and 0.10.
See also #829, #894, #896, and #924.
=> Backport dependence on dwave-preprocessing

dimod/higherorder/polynomial.py
An example of what I have in mind for refactoring BinaryPolynomial as discussed with @arcondello  in #988
With https://toolz.readthedocs.io/en/latest/api.html#toolz.functoolz.excepts, we could include the initial part of BinaryPolynomial  #.__eq__in this treatment
=> refactor & optimize BinaryPolynomial.__eq__

dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py
Provides about a 25% speedup at all sizes in my local testing. Test script:
```python
import itertools
import time
import dimod
num_variables = 2500
qm = dimod.QuadraticModel()
qm.add_variables_from('BINARY', range(num_variables))
qm.add_variable('BINARY', 'a')
t = time.time()
for u, v in itertools.combinations(qm.variables, 2):
qm.add_quadratic(u, v, 1)
print(time.time() - t)
qm = dimod.QuadraticModel()
qm.add_variables_from('BINARY', range(num_variables))
qm.add_variable('BINARY', 'a')
t = time.time()
qm.add_quadratic_from((u, v, 1) for u, v in itertools.combinations(qm.variables, 2))
print(time.time() - t)
```
Output:
```bash
1.094804286956787
0.8172729015350342
```
=> Speed up QM.add_quadratic_from

dimod/higherorder/polynomial.py, tests/test_higherorder_polynomial.py
Just noticed this. It was in the original version too, but it stands out more in the new version
=> fix BinaryPolynomial.__eq__ when args contain different terms

dimod/constrained.py, releasenotes/notes/cqm-set-objective-from-iterables-d1dc8698cc7e42e4.yaml, tests/test_constrained.py
Set objective from an iterable similar to `add_constraint` method.
CQM._iterable_to_qm(iterable) -> QuadraticModel that takes that functionality, then just use that in CQM.add_constraint_from_iterable and CQM.set_objective
Closes #919
=> set_objective from iterables

dimod/reference/composites/_preprocessing.py, dimod/reference/composites/clipcomposite.py, dimod/reference/composites/connectedcomponent.py, dimod/reference/composites/fixedvariable.py, dimod/reference/composites/roofduality.py, dimod/reference/composites/scalecomposite.py, dimod/reference/composites/spin_transform.py
Tested locally the `dwave-preprocessing` install. Credit to @hhtong for the nice commit history that made this very simple.
Closes https://github.com/dwavesystems/dimod/issues/989
=> Don't require dwave-preprocessing to be installed to import dimod

dimod/sampleset.py, docs/reference/sampleset.rst, releasenotes/notes/feature-SampleSet-filter-3faa96ca274c7b17.yaml, tests/test_sampleset.py
This further allows nice syntax like
```python
sampleset.filter(lambda d: not d.is_feasible).first
```
to get the lowest-energy feasible sample.
=> Add `SampleSet.filter()` method

.circleci/config.yml
Not sure why this wasn't failing on the PR before, but it was failing on main so...
=> Update brew in CI OSX for Python 3.10

releasenotes/notes/drop-preprocessing-32e36f9f665cc778.yaml, setup.py
I don't love dropping it with only a patch version increment
but I don't see another way to resolve the circular dependency
issues we're having. The error message at least is pretty
explicit and all of the ocean packages that rely on it have been
updated to also use dwave-preprocessing.
Closes https://github.com/dwavesystems/dimod/issues/1021
=> Drop dwave-preprocessing as a full dependency

dimod/constrained.py
This PR adds a note to the doc string of `ConstrainedQuadraticModel.add_discrete` that helps to clarify why and in what cases this method should be used instead of `ConstrainedQuadraticModel.add_constraint`.
=> Update doc string

dimod/cyvariables.pyx, dimod/serialization/format.py, releasenotes/notes/faster-print-large-sampleset-0a924afbd6ec096f.yaml, releasenotes/notes/feature-variables-slice-0e8295cb69eda2e9.yaml, tests/test_serialization_format.py, tests/test_variables.py
Comparison:
```python
import time
import dimod
import numpy as np
sampleset = dimod.SampleSet.from_samples(np.ones((91, 500000)), vartype='BINARY', energy=np.zeros(91))
t = time.perf_counter()
dimod.serialization.format.Formatter().format(sampleset)
print(time.perf_counter() - t)
```
As an example, running this simple test locally gives `22.33913665200089` without the change and `0.007365263998508453` with.
Also add variable object slicing.
Closes https://github.com/dwavesystems/dimod/issues/1069
Closes https://github.com/dwavesystems/dimod/issues/1068
=> Speed up printing of large sample sets

.circleci/config.yml, dimod/core/composite.py, releasenotes/notes/drop-py-3.6-21e3bf743ccb3841.yaml, requirements.txt, setup.cfg, setup.py
Python 3.6 reached EOL Dec 2021
The NumPy minimum was chosen to still support https://github.com/dwavesystems/penaltymodel/issues/134
=> Raise minimum Python version to 3.7 and minimum NumPy version to 1.19.1

dimod/binary/binary_quadratic_model.py, docs/conf.py, docs/reference/quadratic.rst, releasenotes/notes/restore-to-serializable-a20e3ab59ba9348b.yaml, tests/test_bqm.py
We could also create an equivalent for quadratic models, but I am going to leave that alone for now.
=> Restore BQM.to_serializable and .from_serializable

dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py, dimod/vartypes.py, releasenotes/notes/continuous-0c9da2dbefba3775.yaml, tests/test_quadratic_model.py, tests/test_vartypes.py, testscpp/tests/test_quadratic_model.cpp
Still need sample set support and has some TODOs. Putting this work on the [continuous](https://github.com/dwavesystems/dimod/tree/continuous) branch for now, so I don't just make an enormous patch.
=> Add support for continuous variables in QuadraticModel, Python and C++

benchmarks/qm.py, benchmarks/requirements.txt, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/quadratic/quadratic_model.py
Some minor speedups for `QM.add_variables_from()` and `QM.add_linear_from()`
```bash
Commit: c9fb8c3f <main>
qm.TimeAddLinearFrom.time_add_linear_from [desktop/virtualenv-py3.8]
ok
======== ============= =============
--                  param2          
-------- ---------------------------
param1       dict          list    
======== ============= =============
str     1.07±0.05ms   1.10±0.05ms 
int       332±80μs      295±2μs   
======== ============= =============
started: 2022-04-05 11:00:31, duration: 1.82s
qm.TimeAddVariablesFrom.time_add_variables_from_str [desktop/virtualenv-py3.8]
ok
======== =============
param1               
-------- -------------
str     2.79±0.04ms 
int     1.36±0.01ms 
======== =============
started: 2022-04-05 11:00:32, duration: 808ms
```
```bash
Commit: …
```
=> Speed up QM.add_variables_from() and QM.add_linear_from()

.circleci/config.yml, pyproject.toml, releasenotes/notes/drop-numpy1.19-e71bb3b051194bdb.yaml, requirements.txt, setup.py, tests/test_bqm.py, tests/test_quadratic_model.py
This allows us to build all version of dimod with the same NumPy version which simplifies thing.
=> Drop support for NumPy 1.19

pyproject.toml, releasenotes/notes/oldest-supported-numpy-56de85613d641810.yaml
Although we need some newer features of NumPy at runtime, we can safely build against the older headers. I was not able to detect any performance regressions from doing so.
See https://github.com/dwavesystems/dwave-ocean-sdk/issues/208
=> Use oldest-supported-numpy in pyproject.toml

asv.conf.json, dimod/quadratic/quadratic_model.py, releasenotes/notes/fix-qm.add_linear-performance-regression-8d97458c4a494240.yaml
77fd6af995c2b940dedc4975d320c690aa019b31 (see https://github.com/dwavesystems/dimod/pull/1170) introduced a performance regression. This commit fixes it.
Comparing 0.10.17 to 0.11.0
```
+        311±10μs         646±30μs     2.08  qm.TimeAddLinearFrom.time_add_linear_from(<class 'int'>, <class 'dict'>)
+        322±20μs         630±20μs     1.95  qm.TimeAddLinearFrom.time_add_linear_from(<class 'int'>, <class 'list'>)
1.07±0.04ms       1.69±0.2ms    ~1.57  qm.TimeAddLinearFrom.time_add_linear_from(<class 'str'>, <class 'dict'>)
+     1.06±0.03ms      1.41±0.04ms     1.32  qm.TimeAddLinearFrom.time_add_linear_from(<class 'str'>, <class 'list'>)
```
Comparing 0.10.17 to this commit
```
311±10μs        295±0.8μs     0.95  qm.TimeAddLinearFrom.time_add_linear_from(<class 'int'>, <class …
```
=> Speed up `QM.add_linear_from()`

benchmarks/qm.py, dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, releasenotes/notes/speed-up-qm.from_file-f843fffd8928d4e6.yaml
I hate the duplicated code, but we need to do it this way to maintain binary compatibility, see https://github.com/dwavesystems/dimod/pull/1193.
Gives ~2x speed up on the benchmark problems. Will get a bigger speedup on larger problems.
=> Speed up `QM.from_file()`

dimod/generators/fcl.py, dimod/generators/satisfiability.py, releasenotes/notes/planted-sat-f0200528096b73e3.yaml, tests/test_generators.py
Added planting to random_nae3sat, random_2in4sat, and random_kmcsat problem generators.
Planting in random constraint satisfaction problems is useful for benchmarking, particularly in the SAT phase - problems can be generated with a guaranteed ground state without impacting hardness properties of the problem class. This is useful in benchmarking where knowing the ground state allows unambiguous tests of optimality. Planting is also important with respect to the SAT filter application.
Minor changes to docstrings independent of the planting option are also implemented.
=> Added planting option for random_nae3sat and random_2in4sat, and minor changes to documentation

.circleci/config.yml, releasenotes/notes/loosen-numpy-ae59b80981918338.yaml, setup.py
This makes it easier for packages that depend on dimod to use `oldest-supported-numpy`.
The issue is when a package specifies say `dimod==0.11.0,oldest-supported-numpy` in their pyproject.toml, the pip install fails because dimod requires `numpy>=1.20.0` at runtime.
E.g. https://app.circleci.com/pipelines/github/dwavesystems/dwave-preprocessing/83/workflows/1bd72543-e11d-463d-a56e-5cdcad38f3c9/jobs/2368
So we loosen the range as much as possible. Unfortunately, the oldest supported numpy for Python 3.7 (1.14.5) is missing some pretty key stuff, like `default_rng`. So it's not really practical to support it. That means that [dwave-preprocessing](https://github.com/dwavesystems/dwave-preprocessing) will need to do something like
```
'numpy==1.17.3;python_version<"3.8"', …
```
=> Support numpy>=1.17.3

dimod/include/dimod/quadratic_model.h, dimod/libcpp.pxd, releasenotes/notes/cppbqm-energy-d8bf4cd3632b2c0c.yaml
Needed to resolve the CI failures in https://github.com/dwavesystems/dwave-samplers/pull/24.
=> Expose C++ QuadraticModelBase::energy() to Cython level

.circleci/config.yml
`delvewheel` is not yet used by default for windows builds in CIBW (unlike delocate for macos, or auditwheel for linux), but official
delvewheel shoutout was added to CIBW docs in https://github.com/pypa/cibuildwheel/pull/650.
With `delocate` already used for macos CIBW builds, this PR closes #870.
=> Repair windows wheels using delvewheel (in cibw build job)

dimod/constrained.py, docs/intro/intro_symbolic_math.rst
The right-hand-side of a symbolic comparison must be numeric. This PR spells that out in a few places.
=> Document rhs comparison requirements

dimod/constrained.py, dimod/core/sampler.py, docs/intro/intro_cqm.rst
**Issue description**
Three docstrings were failing doctest due to invalid syntax.
**Changes**
Avoided doctest errors by updating the relevant docstrings to use either ellipses (for when the output varies from run-to-run) or update the output to the correct one.
=> Update docstrings to pass doctest

dimod/sampleset.py, releasenotes/notes/as-samples-from-sampleset-fefda032711b3044.yaml, tests/test_bqm.py, tests/test_quadratic_model.py, tests/test_sampleset.py
Adds missing case from 156d9787978a620d010dd0ddb7bdf168482d1cef. See https://github.com/dwavesystems/dimod/pull/1222
=> Fix as_samples() when given a sampleset and a labels_type

dimod/constrained.py, releasenotes/notes/compactify-cqm-equations-5456497655b5e24d.yaml
NFC
The two separate equality and inequality constraints in the `ConstrainedQuadraticModel` docstring are replaced with single more compact notation that also reflects the structure of the class.
=> compactified CQM equations

releasenotes/notes/Variables._remove-fd4280eb29c6a605.yaml
Release note was missing from 6ba930cf842a58c8593c7f4425678046cb900a42 (https://github.com/dwavesystems/dimod/pull/1246)
=> Add missing release note

.circleci/config.yml, dimod/constrained.py, dimod/serialization/fileview.py, pyproject.toml, releasenotes/notes/python3.11-658b909d4a574d12.yaml, requirements.txt, tests/test_constrained.py, tests/test_discrete_quadratic_model.py, tests/test_serialization_fileview.py
=> Build wheels for Python 3.11

docs/requirements.txt
Currently dimod's ``requirement.txt`` file specifies ``sphinx<4.1.0`` but on Windows that produces a build error:
```
from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (C:\Users\jpasvolsky\.pyenv\pyenv-win\versions\3.10.2\lib\types.py)
```
I upgraded to version 5.2.2 and built with working CPP docs on both unix and windows OSs.
=> Update sphinx version to support Win10 builds

dimod/include/dimod/constrained_quadratic_model.h, dimod/include/dimod/constraint.h, dimod/include/dimod/expression.h, releasenotes/notes/C++-CQM-3d1b9b9c369c14dc.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
Pulls the C++ CQM code from https://github.com/dwavesystems/dimod/pull/1258.
Does *not* implement docs. I am going to do that in a followup PR.
The `Expression` class also has some `not implemented` errors that will need to be implemented. Also will do in a followup PR.
=> Add C++ CQM class

dimod/vartypes.py, releasenotes/notes/callable-BQM.vartype-65fae40b690bd8a5.yaml, tests/test_bqm.py
There are many places in the code like https://github.com/dwavesystems/dimod/blob/273fb86cdb3af495b490db11a1ecc941e44da0d2/dimod/constrained.py#L209 that could be generalized by the ability to call `bqm.vartype(v)`.
It would also allow us to make `QuadraticViewsMixin` much more full-featured.
See also #849
=> Make BQM.vartype callable

dimod/binary/binary_quadratic_model.py, releasenotes/notes/fix-bqm-linear-loading-c552e5a39d6a51e5.yaml
There is still a regression when the BQM has quadratic interactions, but that would be a more invasive fix. Will do that in a followup PR.
=> Fix performance when loading linear BQMs

docs/reference/cpp.rst
Reverts some changes made in 98cb0f08e7a2f313c3f93c751c7e91e5208d5ee9 to enable C++ doc build [here](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/cpp.html)
=> Restore project for C++ SDK doc build

testscpp/tests/test_constrained_quadratic_model.cpp
Written as part of #1284, but generally useful so might as well add it.
=> Add test for C++ Constraint::scale()

dimod/constrained/constrained.py, releasenotes/notes/compress-kwarg-4d7faa35d0bb2fb2.yaml, tests/test_constrained.py
Address the CQM part of https://github.com/dwavesystems/dimod/issues/1235.
Because we use `zipfile` for our CQMs, we get backwards compatibility for free.
=> Add compress kwarg to CQM.to_file()

dimod/binary/binary_quadratic_model.py, dimod/constrained/constrained.py, dimod/include/dimod/abc.h, dimod/include/dimod/binary_quadratic_model.h, dimod/include/dimod/constrained_quadratic_model.h, dimod/include/dimod/constraint.h, dimod/include/dimod/expression.h, dimod/include/dimod/quadratic_model.h, dimod/include/dimod/vartypes.h, dimod/quadratic/quadratic_model.py, docs/intro/intro_samplers.rst, docs/reference/cpp.rst, docs/reference/models.rst
Enables reuse of model descriptions in the SDK with ``.. automodule::`` (currently the descriptions are sourced in both classes and /concepts), adds docstrings to C++ functions.
=> Update c++ docs

dimod/reference/samplers/exact_solver.py, dimod/reference/samplers/identity_sampler.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, releasenotes/notes/sampler-kwarg-only-args-060c1b5ac2615463.yaml
This helps avoid confusing results when switching between samplers.
This is a backwards compatibility break, but a minor one so I think it's safe.
=> Make optional sampler args keyword-only

dimod/include/dimod/abc.h, dimod/include/dimod/expression.h, dimod/include/dimod/quadratic_model.h, releasenotes/notes/expression-fix-variables-performance-f13a65b6a16fa484.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
This provides a pretty significant performance improvement when fixing variables in individual constraints.
```python
import time
import dimod
num_variables = 10_000
cqm = dimod.ConstrainedQuadraticModel()
cqm.add_variables("BINARY", num_variables)
c0 = cqm.add_constraint(((v, 1) for v in range(num_variables)), '==', 1)
expr = cqm.constraints[c0].lhs
t = time.perf_counter()
for v in range(num_variables):
expr.fix_variable(v, 0)
print(time.perf_counter() - t)
```
Gives a time of ~0.15s vs 1.37s on 0.12.4 on my system.
The majority of the improvement comes from optimizing `remove_variable()`. In fact, the C++ `fix_variable()` is not even called from the Python code. I did test adding a dedicated Cython call rather than [using the view](https://github.com/dwavesystems/dimod/blob/5ef7897af313f …
=> Improve the performance of removing variables from expressions

.circleci/config.yml, tests/requirements.txt
Codecov was removed from pypi ([link](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/), [link](https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259), and [link](https://about.codecov.io/blog/message-regarding-the-pypi-package/)).
They recommend using their orb, so let's give that a go.
=> Use codecov's orb rather than their removed pypi package

.circleci/config.yml
Codecov does not support `coverage`'s default file format ([link](https://docs.codecov.com/docs/supported-report-formats)). So we explicitly cast to xml.
=> Generate an .xml file for Python coverage

dimod/constrained/constrained.py, dimod/constrained/cyconstrained.pyx, dimod/include/dimod/constrained_quadratic_model.h, dimod/include/dimod/expression.h, dimod/libcpp/constrained_quadratic_model.pxd, dimod/libcpp/expression.pxd, releasenotes/notes/fix-variables-performance-9c90a58c968aa710.yaml, tests/test_constrained.py, testscpp/tests/test_constrained_quadratic_model.cpp
Add the ability to generate a new model when fixing variables rather than acting on the CQM in-place. This is almost always more performant. For instance, see the times for a 1000 variable and 1000 constraint CQM with different numbers of variables fixed.
Closes #1319
=> Improve the performance of CQM.fix_variables()

dimod/constrained/cyconstrained.pyx, releasenotes/notes/fix-CQM.from_dqm-f9b7b35c91118d0a.yaml, tests/test_constrained.py
The error was due to Cython's automatic type assignment not using a reference resulting in a copy.
=> Fix ConstrainedQuadraticModel.from_discrete_quadratic_model()

dimod/include/dimod/expression.h, releasenotes/notes/expression-remove-variables-4da6fef4b08ee743.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
Will be used in dwave-preprocessing to speed up the removal of small biases.
=> Add Expression::remove_variables() method

dimod/include/dimod/constrained_quadratic_model.h, dimod/include/dimod/expression.h, releasenotes/notes/fix-quadratic-cqm-fix-variables-43f21519357c228f.yaml, testscpp/tests/test_constrained_quadratic_model.cpp
Closes https://github.com/dwavesystems/dimod/issues/1351
=> Fix Expression::fix_variables() for quadratic expressions

dimod/sampleset.py, dimod/serialization/utils.py, releasenotes/notes/sampleset-serialization-replace-float-with-int-5a3133c66480b8f4.yaml, tests/test_serialization_utils.py
This does come with a performance hit. However it is relatively minor. Testing two edge cases on my system
```python
import time
import dimod
import numpy as np
arr = np.full((100, 500000), 1, dtype=float)  # can be converted
t = time.perf_counter()
dimod.serialization.utils.serialize_ndarray(arr)
print(time.perf_counter() - t)
```
takes `~5.5` seconds on this branch and `~1` second on dimod 0.12.10.
```python
import time
import dimod
import numpy as np
arr = np.full((100, 500000), 1.5, dtype=float)  # cannot be converted
t = time.perf_counter()
dimod.serialization.utils.serialize_ndarray(arr)
print(time.perf_counter() - t)
```
takes `~3.5` seconds on this branch and `~1` second on dimod 0.12.10.
For context, actually Json-serializing the resulting object at this scale takes `~27.8` …
=> Convert floats representing integers to int in sample set serialization

dimod/include/dimod/abc.h, dimod/include/dimod/expression.h, dimod/include/dimod/quadratic_model.h, dimod/include/dimod/utils.h, releasenotes/notes/QuadraticModelBase.remove_variables-e65ed0c138c3ed75.yaml, testscpp/tests/test_binary_quadratic_model.cpp, testscpp/tests/test_quadratic_model.cpp, testscpp/tests/test_utils.cpp
And overloads for base classes.
This significantly improves the performance of `Expression::remove_variables()`.
Testing was done with the following script. The version implemented in this PR was named `remove_variables2`.
```c++
// g++ -std=c++11 -DNDEBUG -g -O3 scratch.cpp -o scratch.out -I dimod/include && ./scratch.out
#include <chrono>
#include <iostream>
#include <vector>
#include <unordered_set>
#include "dimod/binary_quadratic_model.h"
#include "dimod/constrained_quadratic_model.h"
int main(int argc, char* argv[]) {
const int num_variables = 250000;
std::vector<int> variables;
for (int i = 0; i < num_variables; i += 2) {
variables.emplace_back(i);
}
auto bqm = dimod::BinaryQuadraticModel<double>(num_variables, dimod::Vartype::BINARY);
auto cqm1 = …
```
=> Add QuadraticModelBase::remove_variables() method

dimod/constrained/constrained.py, releasenotes/notes/check-overlaps-keyword-in-add-discrete-f078c11e943cfb41.yaml, tests/test_constrained.py
As discussed in the issue #1364, the variable check in `ConstrainedQuadraticModel.add_discrete` method  can be skipped in some cases and the user can decide if this is truly necessary. 
This is implemented by adding a `do_var_check` boolean variable (default: `True`), which enables the check if it's true, in the methods `ConstrainedQuadraticModel.add_discrete_from_model`, `ConstrainedQuadraticModel.add_discrete_from_comparison`,  and `ConstrainedQuadraticModel.add_discrete_from_iterable`.
=> Addressing issue #1364: option for a variable check in add_discrete method

dimod/views/quadratic.py, releasenotes/notes/add-quadratic-from-52f923c89ce762cb.yaml, tests/test_constrained.py
While there is a method `ConstrainedQuadraticModel.objective.add_linear_from()`, which adds linear biases to the objective, there is no corresponding method for quadratic biases.
Here, we add a method `ConstrainedQuadraticModel.objective.add_quadartic_from()` to allow adding quadratic terms to the objective in a similar way to the linear biases. We also add an abstract method `ConstrainedQuadraticModel.objective.add_quadartic()` to be overloaded in the subclasses.
Closes the issue https://github.com/dwavesystems/dimod/issues/1367
=> add method `ConstrainedQuadraticModel.objective.add_quadartic_from()` 

dimod/include/dimod/abc.h, releasenotes/notes/QuadraticModelBase.remove_interactions-1580cb5e00bc96f4.yaml, testscpp/tests/test_quadratic_model.cpp
This is designed to be used by `dwave-preprocessing` to speed up the removal of small biases.
=> Add QuadraticModelBase::remove_interactions() method

.circleci/config.yml
I'll uncap the NumPy version in another PR (i.e., https://github.com/dwavesystems/dimod/pull/1373).
See also https://github.com/dwavesystems/dwave-ocean-sdk/issues/294.
=> Use M1 resource class for macos builds on CircleCI

.circleci/config.yml, dimod/binary/cybqm/cybqm_float32.pxd, dimod/binary/cybqm/cybqm_float64.pxd, dimod/binary/cybqm/cybqm_template.pxd.pxi, dimod/binary/cybqm/cybqm_template.pyx.pxi, dimod/constrained/cyconstrained.pxd, dimod/constrained/cyconstrained.pyx, dimod/constrained/cyexpression.pyx, dimod/cyqmbase/cyqmbase_float32.pxd, dimod/cyqmbase/cyqmbase_float64.pxd, dimod/cyqmbase/cyqmbase_template.pyx.pxi, dimod/cyutilities.pxd, dimod/cyutilities.pyx, dimod/discrete/cydiscrete_quadratic_model.pxd, dimod/discrete/cydiscrete_quadratic_model.pyx, dimod/discrete/discrete_quadratic_model.py, dimod/quadratic/cyqm/cyqm_float32.pxd, dimod/quadratic/cyqm/cyqm_float64.pxd, dimod/quadratic/cyqm/cyqm_template.pyx.pxi, dimod/typing.pxd, pyproject.toml, releasenotes/notes/remove-numpy-build-dependency-9a5cd6a9661dcde7.yaml, requirements.txt, setup.py
This will make NumPy 2.0 support much easier. Will do that in a followup PR.
Contains the commits from https://github.com/dwavesystems/dimod/pull/1374. I will rebase once that one is merged.
=> Remove build-time dependency on NumPy

dimod/core/structured.py, dimod/decorators.py, dimod/generators/wireless.py, dimod/quadratic/quadratic_model.py, dimod/reference/composites/structure.py, dimod/reference/samplers/identity_sampler.py, dimod/reference/samplers/random_sampler.py, dimod/reference/samplers/simulated_annealing.py, dimod/testing/asserts.py, dimod/variables.py, docs/intro/intro_scaling.rst
Part of [sdk](https://github.com/dwavesystems/dwave-ocean-sdk/pull/300), [dwave-system](https://github.com/dwavesystems/dwave-system/pull/524), [dwave-cloud-client](https://github.com/dwavesystems/dwave-cloud-client/pull/633), and [dwave-hybrid](https://github.com/dwavesystems/dwave-hybrid/pull/294) PRs to reduce build warnings
The updates in this dimod PR reduce the number of warnings by half (<70 left).  
Additional minor update: Pyments does not have an `ipythonconsole` lexer so dimod was producing `Could not lex literal_block as "python"` warnings so switched to the standard Python console for those examples.
=> Remove ambiguous xrefs to reduce build warnings

docs/intro/intro_scaling.rst
[This commit](https://github.com/dwavesystems/dimod/pull/1372/commits/4f3dcf3c471a5d1871d90b302a576a40fba80a2d) fixed lexar warnings on unsupported `ipythonconsole` but unfortunately [this commit](https://github.com/dwavesystems/dimod/pull/1372/commits/80fbae59f3608ce86e48d169a1577932de8600ba), in response to [this review comment](https://github.com/dwavesystems/dimod/pull/1372#discussion_r1653270133), introduced a new lexar problem, `WARNING: Could not lex literal_block as "python"`. 
This PR fixes these new warnings.
=> Fix lexar warning on ipython prompt

docs/Doxyfile
This is to get rid of the doxygen warnings below. Alternatively one can upgrade the Doxyfile but I see that our build uses version 1.9.1 and my systems won't go down that low (and the upgrade mainly updates comments).
I also replaced defaults for verbosity with env variables so we can run with fewer warnings in CircleCI and with warnings locally and in RTD builds. Execution should continue to use the defaults unless one sets these new env variables in the conf file, something like: 
```
if os.environ.get('CI', False):
subprocess.call('cd ../minorminer/docs/; DOXYGEN_QUIET=YES make cpp', shell=True)
...
```
```
warning: Tag 'TCL_SUBST' at line 247 of file '-' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u" …
```
=> Doxyfile update

dimod/constrained/constrained.py, releasenotes/notes/feature-CQM.iter_constraint_data-labels-9ffdc5a2db6f09c4.yaml, tests/test_constrained.py
See https://github.com/dwavesystems/dimod/issues/1381. This addresses one of the options laid out.
=> Add labels keyword argument to CQM.iter_constraint_data()

dimod/binary/binary_quadratic_model.py, dimod/constrained/constrained.py, dimod/discrete/discrete_quadratic_model.py, dimod/generators/anti_crossing.py, dimod/generators/wireless.py, dimod/quadratic/quadratic_model.py, dimod/sym.py, dimod/utilities.py
importing dimod currently results in a number of syntax warnings due to invalid escape sequences in docstrings in recent python versions (see #1370). This just prevents the warnings by marking the offending docstrings as `r"raw string literals"`
=> prevent syntax warnings for invalid escape characters

dimod/sampleset.py, releasenotes/notes/add-sampleset.wait_id-as-proxy-to-qpu-future-9de9fbbc3dbc2285.yaml, tests/test_sampleset.py
=> Propagate `.wait_id` from future to `SampleSet`

dimod/reference/composites/tracking.py, releasenotes/notes/TrackingComposite-OrderedDict-to-dict-073323bc352bc35d.yaml, tests/test_trackingcomposite.py
`TrackingComposite` was added while we still supported Python 2.7 (https://github.com/dwavesystems/dimod/pull/484). Now that `dict` is ordered, we can just use `dict` rather than `OrderedDict`.
Closes https://github.com/dwavesystems/dimod/issues/1395
=> Use dict rather than OrderedDict in TrackingComposite

dimod/generators/multi_knapsack.py, docs/reference/generators.rst, releasenotes/notes/quadratic-multi-knapsack-generator-6bd6daf629f11399.yaml, tests/test_generators.py
A quadratic multiple knapsack generator that allows for custom values, weights, profits and capacities.
@arcondello: @eordog and I chatted about whether it makes more sense for the diagonal of `profits` to be the `values` instead of passing `values` in as a separate array. Some of her benchmarking datasets have `values` as a separate array and some have it as the diagonal of `profits`. Curious if you have any thoughts on this. I went with separate as that's how I did it for `quadratic_knapsack`, whatever we end up going with I think these two functions should be consistent.
=> Add Quadratic Multi Knapsack Generator

docs/reference/generators.rst
the relevant code: https://github.com/dwavesystems/dimod/blob/ac4dcbb7424db6b6a14448ec84f0f04bbbd8b80f/dimod/generators/multi_knapsack.py#L23
=> Fix `multi_quadratic_knapsack` from #1397

dimod/utilities.py, releasenotes/notes/fix-variables-relabel-c145815df427c55c.yaml, tests/test_variables.py
Looking through the logic, I think it would be possible to avoid the copy with a more significant rework. But we already are doing many copies and traversals in that family of functions so IMO the simpler approach is best.
Closes #1408
=> Fix Variables._relabel() with supersets
